### ISSUE TITLE
Solo mining

### ISSUE THREAD

**Issue by tz161** [nwoolls/MultiMiner#115]
Excuse the basic question,,, how do i solo mine using multiminer, 
thanks in advance

**Comment by modderchris** [comment]
that link is useless

**Comment by nwoolls** [comment]
@modderchris this has nothing to do with MultiMiner - help yourself by seeking out answers from those who actually solo mine. This is not a MultiMiner "issue".

**Comment by modderchris** [comment]
the link is useless no matter what the issue is therfore this issue cannot reasonably be closed

**Comment by nwoolls** [comment]
@modderchris I tell you what - I'll go work on writing a how to guide because you demanded one. You stay here and keep hitting refresh until you see one.

**Comment by modderchris** [comment]
thanks a guide would really be great since many people are getting into mining (hence the ridiculous gpu prices)

**Comment by modderchris** [comment]
I also have an issue with bfgminer crashing after 30-60 seconds on amd rx-550 512stream 2048mb ram with an amd 970 chipset and athlon II x3 450 with a fourth unlocked stable core

**Comment by flotsam2000** [comment]
Hmmm Apparently this thread and thread.multiminerapp.com are both dead. Does anyone know of a way of setting up multiminer for solo mining using localhost for altcoins and eight GPUs? I use multiminer every day for pools, but I want to switch to solo mining for more obscure coins with my old rig
