### ISSUE TITLE
Multiminer and Raspberry Pi

### ISSUE THREAD

**Issue by chrishaefner** [nwoolls/MultiMiner#187]
Is multiminer able to run with a raspberry pi?

**Comment by chrishaefner** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Christopher

Accept: http://www.linkedin.com/blink?simpleRedirect=0MczcQe3cRcjsRc3cUd3gMe3ARfkh9rCZFt65QqnpKqipNrk8VoRwPjjRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CgPbnxIsjBVc3tFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980448321787957248_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=p3cJu6NNenAMdSAJsSYRe3lKfmhFpipxkAFgs6NCiT0JujgMs45WjmJkiCtCuCRidBF9onBcs6RUiAZLoQB8hntql45bkjxkemJEiDAOpBYVoBlfgPxBdAMNiz1lgAUPenhnqQlJsSdgpQxeu31qe6ZNe6dgikd2cn9Me5YRkSERl5lhiBwTrARqr5ZWq6Zxu59lszpamCVQiDwTjSJKtmJQinhehAEPtPlOlCNShChHiSxecj5TpQoSujkOilB6qR9Qelh6kPtSlk51gk5EulEJe5kTcT9ahB51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CgPbnxIsjBVc3tFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5980448321787957248_500&amp;markAsRead= Learn why we included this at the following link: http://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CgPbnxIsjBVc3tFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980448321787957248_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by chrishaefner** [comment]
Christopher Haefner would like to connect on LinkedIn. How would you like to respond?

Accept: http://www.linkedin.com/blink?simpleRedirect=0MczcQe3cRcjsRc3cUd3gMe3ARfkh9rCZFt65QqnpKqipNrk8VoRwPjjRVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CMQbmVLq6EMcPtFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980448321787957248_500&markAsRead=

View Christopher Haefner&#39;s profile: http://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9CMQbmVLq6EMcPtFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980448321787957248_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9jsOdSkSczcMpmcVdz5xczAPdChxdm8Mcj4Mc30Mc30MpCcOejARpj8PdScOcjBzcS8UpC5Ap3hxczBAdz1xdP9ycPdzpz5Ap68Ve69BoPAMozsMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0OcPgUcPkNdPkMcPwQd30UejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9CMQbmVLq6EMcPtFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980448321787957248_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=1Id2RKrSxGc3cTqiRPrPkUdmUZp6BB9DFFiRhdcmB2t7ASm4lfbkh1h4sSkjBxgzsViAl7q7d2ukRadR5GrRxct4ZUoDxhukZ9cmINjB8JgS5HqRFRt6t2blgTq4tUjSJJrPBJhjlzqmQUgAFdkz51piRqjCFNondaoTdgtPkJpT5pjTdGujlzhPlmgBoMrAJhlkhOdzl3cjp7jPxzoS5Dm7F8jPkUcP1VuAtPd3pnrk96rAR1qDwNgkBGuB13qjxUc4piq3BQgTtlgk51tP4RjTFJcP4QsSV5kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CMQbmVLq6EMcPtFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5980448321787957248_500&amp;markAsRead= Learn why we included this at the following link: http://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CMQbmVLq6EMcPtFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980448321787957248_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by chrishaefner** [comment]
Christopher Haefner would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0MczcQe3cRcjsRc3cUd3gMe3ARfkh9rCZFt65QqnpKqipNrk8VoRwPjjRVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CASbn5KoDhOoztFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980448321787957248_500&markAsRead=

View Christopher Haefner&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9CASbn5KoDhOoztFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980448321787957248_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9jsOdSkSczcMpmcVdz5xczAPdChxdm8Mcj4Mc30Mc30MpCcOejARpj8PdScOcjBzcS8UpC5Ap3hxczBAdz1xdP9ycPdzpz5Ap68Ve69BoPAMozsMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0OcPgUcPkNdPkMcPwQd30UejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9CASbn5KoDhOoztFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980448321787957248_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1FdyRNrC9QsC8TqiRPrPkUdmUZp6BB9CBFgll1ljhWjPpgcQJFclFJkzBzsSNcqThfcA56u6VcpQxmt4kStQ8TejcTqQFviBhId4xSqABitnBggQlNtBdksR9cul9AcQ9qhk5LtzdbgDBaoRFhjn1buBBppSh1gBdWcORqcCBju4Nqsz9Np5hMuBBChA9Ri7FdkzoTmAper4ITtz8Uu4dCk7FkkmJFsm9Em4FyjPtqsT9eq6QPkl8TpRxdr6hhhSZamBcMq5Ziqntlgk51pQ9hdPh2q7xBtnx5kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CASbn5KoDhOoztFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5980448321787957248_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CASbn5KoDhOoztFbndLdjwRrzRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980448321787957248_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by chrishaefner** [comment]
Hi nwoolls/MultiMiner,

I'd like to add you to my professional network on LinkedIn.

- Christopher

Confirm that you know Christopher: https://www.linkedin.com/e/v2?e=0-iimsbfch-zm&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=M3Xc9Bmq&invitationId=5980448305715384320








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iimsbfch-zm&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQF0UL9Vf7T7zQAAAVHdL390MXPcmXWz-MZAIjY_EsABTbhRUOmOfVdBKi3BdkG0AUQS8P7fv6YlJUC-02UfAdt2T4VfbKNLYjISzRam16_bKd8H1MEM6HsVkJpnedQ0rfsLuEPNEAQdmg49lL3g-PyDbXFJcq7hJ9HkqKofQt7TOYw2cAFr2XbP-vkv1AtMiLnk&eid=0-iimsbfch-zm


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iimsbfch-zm&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chrishaefner** [comment]
Christopher Haefner would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=n585os-ij0f2806-g9&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=M3Xc9Bmq&invitationID=5980448305715384320

View Christopher Haefner&#39;s profile: https://www.linkedin.com/e/v2?e=n585os-ij0f2806-g9&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=M3Xc9Bmq&invitationID=5980448305715384320





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=n585os-ij0f2806-g9&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=n585os-ij0f2806-g9&loid=AQHkBZ2XBXrChgAAAVIO37twpYrEqhh_RzH1g-GsxpjgHdSMPK6Y-LHf_zqcooMLdFfOpnUHtFprFu__k49sxwH9XTdrBBBA5nqXYD9LCm8O2niQyXpn7Jf4hvXgFozJhXX_9vhwXtH-XvLGEehjG2oNR5srdQ8kv7zhXyoZaR22r8QVmOBY6F2MhDGlhnFcQAhH

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=n585os-ij0f2806-g9&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Grantrocks** [comment]
Hey so did this work?
