### ISSUE TITLE
Memory leak...

### ISSUE THREAD

**Issue by Netzarim** [nwoolls/MultiMiner#189]
I've updated to 3.8.3.340 on two machines this morning.  One is using an AMD proc, the other is Intel.  On both machines memory utilization fro MultiMiner.Win.exe is spiraling out of control.  It is causing the systems to be unusable and freezing.  I have the Intel one with me, it is an i7, and currently memory is at 7G on this process... When I left home this morning, the system for the AMD was all but hung with over 4G memory and increasing.. 

The update was done through the application, not as a download and re-install...   I just pulled the latest, and re-installed and still seeing the same problem...

**Comment by nwoolls** [comment]
Can you please post the output of ipconfig on both systems. Sounds like you have adapters on class B or A subnets.

**Comment by nwoolls** [comment]
Fixed in 359480f089173664f79d94874f0a9683bdc80961

**Comment by Netzarim** [comment]
Working great.  Thanks.
