### ISSUE TITLE
No Copy of BFGMiner was detected

### ISSUE THREAD

**Issue by vecdid** [nwoolls/MultiMiner#190]
After install multiminer starts and I get the error No copy of BFGMiner was detected. Would you like to download and install. I choose yes and then I get another error. I get downloading and installing from luke something or other then the error comes up 

Copy file.

An unexpected error is keeping you from copying file. If it continues blah blah blah. 

Error 0X80004005: Unspecified Error

bfgminer.exe and for bfgminer-rpc.exe

**Comment by nwoolls** [comment]
Please post the full text of any errors instead of "blah blah blah"
