### ISSUE TITLE
Installation/Running in Ubuntu 12.04

### ISSUE THREAD

**Issue by JEasyJEasy** [nwoolls/MultiMiner#191]
Hello. Love your tool. I'm a user on windows8/Mobile and just recently switched to Ubuntu. I was hoping to easily install and run but I haven't been able to get the program to run after installation.  

I am followiwing the instructions for Linux found here: https://nwoolls.github.io/MultiMiner/. Everything is fin until I follow the last command which is  "mono multiminer.win.exe". I was not able to locate any alternate instructions across the web that did not refer to that executable. Any advice? 

Thanks. I love the tool.

**Comment by nwoolls** [comment]
What is the output of running mono MultiMiner.Win.exe? Note that Linux is case sensitive so you need to get the file name correct.

There are instructions here as well though they should be the same:

https://github.com/nwoolls/MultiMiner/wiki/Installation#linux-installation-debian-based

**Comment by JEasyJEasy** [comment]
Thank you.  Good point on case sensitive. I was cutting pasting from the instructions (after trying typing) so that isn't an issue in this case.  Here is what I get back: 

Cannot open assembly 'MultiMiner.Win.exe': No such file or directory.

**Comment by nwoolls** [comment]
The instructions at that point are not line-for-line. You need to unzip the zip file and then open up a Terminal window. You'll need to change directory into the folder where you extracted the files before running the mono command. You need to be in the Terminal, in the folder where MultiMiner.Win.exe (and the rest of the files) are.

**Comment by JEasyJEasy** [comment]
I have extracted the MultiMiner-3.8.4 and it does not contain MultiMiner.Win.exe

**Comment by nwoolls** [comment]
Yes it does. You can verify it yourself on Windows.

**Comment by JEasyJEasy** [comment]
Ok. Sorry to have even brought this up. You are absolutely correct. I was looking into the extracted folder from the .zip source code. I'm guessing it's pretty obvious now that most people getting this error message have simply extracted the wrong package or as in my case extracted multiple similar named packages and looked in the wrong folder. Thanks so much!

**Comment by nwoolls** [comment]
No problem at all - some of the GitHub generated pages are confusing. All of the "release" downloads (not source) can be gotten from http://releases.multiminerapp.com.
