### ISSUE TITLE
App don't open

### ISSUE THREAD

**Issue by chemarbgmailcom** [nwoolls/MultiMiner#192]
I cannot open the multiminer app. The process took 28% of CPU and the application window never opens.

I have been using multiminer in this laptop before, but now I am unable to run it

**Comment by chemarbgmailcom** [comment]
![captura](https://cloud.githubusercontent.com/assets/10392310/5607222/a76f5048-9449-11e4-96ae-c32bb499c718.PNG)

Screen capture. OS is Windows 7 x64

**Comment by nwoolls** [comment]
Try different releases from the following page to try to determine the version causing the problem:

https://github.com/nwoolls/MultiMiner/releases

**Comment by chemarbgmailcom** [comment]
Thanks.

"Older" version I can "run" is version 2.1.0, and still doesn't run. Older versions get blocked by the antivirus.

**Comment by nwoolls** [comment]
So something has changed on your setup, not in a MultiMiner release or version.

You can try deleting your MultiMiner settings. Open the Windows File Explorer and navigate to %appdata% in the address bar. Move the MultiMiner folder to your desktop and try launching again.

**Comment by chemarbgmailcom** [comment]
I think you are right, something must be bad on this laptop, on other computer the apps opens fine. I have deleted the "app data" and the application re-creates the folder, and only one file on the folder (AlgorithmConfigurations.xml)

**Comment by nwoolls** [comment]
Try waiting as long as you can manage to see if an error eventually occurs. You can also try the Event Viewer in Windows under the Applications section. Check for errors for today's date.

**Comment by chemarbgmailcom** [comment]
After some hours stills doesn't open and windows event log don't throw any errors. Could I send you a process dump?

**Comment by jgb211** [comment]
Hello, I'm trying to run multi miner it will not launch either by double click the short cut nor by terminal under OS X this is what i get on the ter. 
![screen shot 2016-03-29 at 10 11 52 am](https://cloud.githubusercontent.com/assets/18145286/14111411/9d0d53fa-f598-11e5-9dc2-2f77cee7cfad.png)

**Comment by nwoolls** [comment]
Please try the latest releases, they have several fixes for launching the app on macOS.
