### ISSUE TITLE
Cannot connect to any pools, states they are all invalid

### ISSUE THREAD

**Issue by phildobaggins** [nwoolls/MultiMiner#193]
I haven't run the program for a while, just opened it up, updated to the current version and I can no longer mine.  I have two zuesminer fury miners and I've never had a problem before.  No matter what pool or what coin I put in, it will no longer let me mine.  

The specific error is "none of the pools configured can be used".

**Comment by nwoolls** [comment]
Sounds like your pools are either down or you are having network issues. You can verify though by installing one of the older releases to see if it remedies the issue:

http://releases.multiminerapp.com

If one of the previous releases resolves the issue let me know.

**Comment by phildobaggins** [comment]
I tried going all the way back to 3.4.5. didn't work.

**Comment by phildobaggins** [comment]
Using multipool.us and everything appears to be up on their end.

**Comment by nwoolls** [comment]
That doesn't sound like a MultiMiner problem. If you run the underlying BFGMiner you should see the same results. You can launch BFGMiner directly from the Process Log screen using the right-click menu:

https://github.com/nwoolls/MultiMiner/wiki/Process-Log#process-log

Maybe something in your settings changed? You can try closing MultiMiner and then moving the MultiMiner folder found in %appdata% (type that into the address bar in Windows).

**Comment by phildobaggins** [comment]
Ok, will try it

**Comment by phildobaggins** [comment]
Same result.

**Comment by nwoolls** [comment]
What are the arguments (you can copy / paste from the Process Log)? Sounds like something to report to either Multipool.us or BFGMiner.

**Comment by phildobaggins** [comment]
--scrypt --scan noauto -o stratum+tcp://us-west.multipool.us:3334/ -u phildo83.1 -p x -S zeusminer:\\.\COM4 -d zeusminer@\\.\COM4 -S zeusminer:\\.\COM8 -d zeusminer@\\.\COM8 --api-listen --api-port 4028 --api-allow W:127.0.0.1, -T -q --log 5

**Comment by nwoolls** [comment]
Looks fine - and what does BFGMiner output?

**Comment by phildobaggins** [comment]
it's saying no servers found.

**Comment by nwoolls** [comment]
I would report this to either BFGMiner or Multipool.us.

**Comment by phildobaggins** [comment]
Ok, thank you very much for your help.  I really do like the program, it's been great!

**Comment by nwoolls** [comment]
My pleasure - sorry we couldn't get things working.
