### ISSUE TITLE
Just a thought for the app

### ISSUE THREAD

**Issue by chrishaefner** [nwoolls/MultiMiner#196]
Hi,
So I just had a thought.  I would like to see (even if it was only a link) a list of up and coming/best profit mining pools. Maybe just for the people with the paid subscription?  Just something I'd like to see.  Thank you for all your hard work! I absolutely love multiminer!

**Comment by Clearik** [comment]
Unfortunately a lot of mining pools are scams. I'm sure nwoolls would hate to advertise a certain mining pool, and then that mining pool go on to steal people's coins.

Also, I'm sure he wouldn't want to be accused of showing favoritism to one mining pool over another.

Just my opinion, though.

**Comment by nwoolls** [comment]
@Clearik is pretty dead on there. I try very hard not to encourage or endorse any one pool as that is a slippery slope.

That said there is already a feature in MultiMiner that will advise you to look into coins that are, for instance, more profitable than the ones you are mining:

https://github.com/nwoolls/MultiMiner/wiki/Settings#advanced-service-settings

**Comment by chrishaefner** [comment]
Okay thank you for the feed back. I will just have to play around with some pools and see what I like best and what is most stable.
