### ISSUE TITLE
Multiple bfgminer.exe tasks

### ISSUE THREAD

**Issue by ShosMeister** [nwoolls/MultiMiner#197]
been noticing this for a while and think it's related to an interruption of internet service or the pools being down but what seems to happen is that MM launches multiple copies of bfgminer.exe - currently have 780 running according to task manager - and they can not be killed. I need to reboot to clear them.
![mm_01](https://cloud.githubusercontent.com/assets/10685152/5887709/97a90d74-a3ae-11e4-8c47-625871190515.jpg)
![mm_02](https://cloud.githubusercontent.com/assets/10685152/5887710/97accaea-a3ae-11e4-8fd8-021f71703d4d.jpg)

**Comment by nwoolls** [comment]
Without more information I'd say this is an issue specific to your system.

It seems to me like BFGMiner is getting locked up to the point where A) MultiMiner sees it is dead and spawns another instance but B) Neither MulitMiner nor the OS can kill the locked process.

I've seen this myself with SGMiner on systems that aren't entirely stable. It was impossible to kill the process without rebooting.

If that doesn't sound like the case, please try rebooting and observing to see when the processes spawn and why. Also see if you can actually End Process (via the button there) or if you get a message saying the process cannot be terminated.

**Comment by ShosMeister** [comment]
Realize there wasn't a whole lot of info but thought it was enough given the circumstances. When I try to kill the process, I get no feedback/error just returns. The only time I've seen this happen is if there was an interruption of internet/pool connectivity. Why would MM think the process is dead and spawn a new one knowing it could not kill the previous. Plus, why can't it be killed? That makes no sense to me. Will see if I can get more evidence but haven't seen any other symptoms.

**Comment by nwoolls** [comment]
Does the Process Log show that MultiMiner is starting new instances of BFGMiner due to a "frozen miner"?

**Comment by ShosMeister** [comment]
Not sure where to find the process log.

**Comment by nwoolls** [comment]
I linked to the help for it in an earlier reply to you:

https://github.com/nwoolls/MultiMiner/wiki/Process-Log#process-log

**Comment by ShosMeister** [comment]
Sorry. Saw that but didn't see where to get to it. Never really noticed the small icons on the left until now :)

 

I'll run it for a while and take a look at that the next time it fails.

 

Thanks!!

**Comment by nwoolls** [comment]
Sure thing - I updated the help page with a bit more text to direct the user to the left-hand toolbar.

**Comment by nwoolls** [comment]
Closing due to no response - please reopen if issues persist.
