### ISSUE TITLE
multiminer disapearing

### ISSUE THREAD

**Issue by daemonblackheart** [nwoolls/MultiMiner#198]
every few days i have to reinstall multiminer as it just disapears ie last night i checked my status this morning multiminer is gone and had to be reinstalled however all settings stay in place it just disapears all together when i perform a search the .exe cant be found ( well it does but then states it cannot be located

**Comment by nwoolls** [comment]
Sounds like you have an Antivirus or something else deleting it. That is not a function or feature or something that MultiMiner could or would be doing itself.

**Comment by daemonblackheart** [comment]
fyi i figured out that it was the option to restart mining every x hours that was doing it once i turned that option off it hasnt happened since

**Comment by nwoolls** [comment]
Glad you were able to figure it out but, again, apps do not delete themselves. Something else on your system is deleting the files.
