### ISSUE TITLE
Antminer S5 not detected

### ISSUE THREAD

**Issue by phalanx2** [nwoolls/MultiMiner#199]
I've just recieved a shipment of Antminer S5's and they are not being detected.  I have another montioring software that I use as well and it detects them on port 4028. They also use cgminer version 4.8.0

**Comment by nwoolls** [comment]
Are you able to set me up with remote access to the PC? If so you can contact me at nwoolls @ gmail.com.

The detection code itself is pretty simple. It goes through the IPs on your subnet, tries ports 4028 - 4030, and sends the "VERSION" command to those that respond. It checks that the RPC server responds to the "VERSION" command with a proper response.
