### ISSUE TITLE
Cant download the files all 3 are bad crc

### ISSUE THREAD

**Issue by elpino** [nwoolls/MultiMiner#200]
Try on 2 pcs and on my MAC the zip files are corrupted and exe file.

**Comment by nwoolls** [comment]
I think it is a problem on your end - either your network or Internet connection. There are so far 533 folks that have successfully unzipped and run the latest version released a couple of days ago.

**Comment by elpino** [comment]
i can record a video if you want... i have 20 megas download / 3 megas upload no problem download anything else than this.... is there a certain way i have to download it? cause i tried 2 pcs and my macbookpro.. never seem this problem, any other place i can download the files or an online a link to dropbox or something like that.

**Comment by nwoolls** [comment]
Any of the links on http://releases.multiminerapp.com

**Comment by elpino** [comment]
Im new to mining just want to start doing it.. i downloaded and install guiminer and download like any other file but the ones on the link here they download alright but the zip files dont extract try the app that comes with mac and stuff it..

**Comment by elpino** [comment]
Dont know what else to to download the files a friend told me to install jdownloader to see if i can download it with that program it has a link grabber that i can paste the link to download the file, i will post back if it works.

**Comment by elpino** [comment]
Thanks for your patience.. got to the bottom of the problem use jdownloader and the files downloaded fine, but the real problem lied on Avast anti virus i have it on the Windows and mac Systems it was not letting me download the .exe files and corrupting the .zip files, again thanks for your patience i will try to install now to check it out.

Regards
Alex
