### ISSUE TITLE
Support For Rock Miners

### ISSUE THREAD

**Issue by poncawarrior** [nwoolls/MultiMiner#201]
The program does not find my rock miners - 32/37 GHZ - is there a way to find them using your program??? Thanks

**Comment by nwoolls** [comment]
If you are talking about the original R-Box from RockMiner make sure you have the proper drivers installed:

https://github.com/nwoolls/MultiMiner/wiki/Drivers#silicon-labs-usb-to-uart-driver

**Comment by poncawarrior** [comment]
Yes it's the - RockMiner R-BOX 32 -37 GH/s  - I have the drivers installed - I can run the cgminer they supply - and works okay - but I like your program and would like them to run under it. I'll fiddle around with it and what I can do Thanks Steve

**Comment by poncawarrior** [comment]
Okay - in order for me to get the Rock Miner r-box to work - I had to reinstall the drivers cp2120 USB to UART Bridge Controller and not install the win usb driver. using  zadiag - and there mining away now - Thanks Steve

**Comment by nwoolls** [comment]
That is correct. The drivers that CGMiner uses will almost always uninstall the ones required by MultiMiner (and BFGMiner on the backend) and vice versa.

**Comment by poncawarrior** [comment]
setting up the win usb - made it where it could not be found - so I didn't install them - to see if your program would find the miners and it did.  Thanks again mining at 260 GHZ -
