### ISSUE TITLE
MultiMiner-3.9.2.exe not a valid Win32 application?

### ISSUE THREAD

**Issue by ArchitectOfMind** [nwoolls/MultiMiner#202]
Iv installed MultiMiner successfully on windows 8.1 and windows xp, however when I attempted to install it with windows 7,  I ran into all sorts of strange problems. Initially, attempting to download the .exe file resulted in chrome saying that the "download failed", and provided no further useful information. I was still able to download the file on my windows 8.1 laptop, and so I copied the .exe file from this onto a flash drive and then copied it from the flash drive onto the win 7 computer. As soon as I tried to run it, an error message informed me that the file no longer existed, and the icon was deleted from the desktop. It also deleted the copy stored on the flash drive at the same time. The next day, I was able to download the file, but trying to run it resulted in an error message that informed me that it is "not a valid win32 application". I also downloaded the .zip file, however, after unpacking it, I found that it does not include the installer. If anybody has any ideas on what the problem could be, or potential solutions, it would be greatly appreciated.

**Comment by nwoolls** [comment]
Try disabling any Anti-Virus you may be running.

**Comment by ArchitectOfMind** [comment]
I turned off my anit-virus, and it did not fix the problem... What about the zip folder, that did not have the installer in it at all. I feel like this is a really stupid question, but how do I install it from the .zip folder?

**Comment by nwoolls** [comment]
You don't you just extract the zip folder contents and run the executable.

**Comment by ArchitectOfMind** [comment]
the .exe for 4.0 works.

**Comment by nwoolls** [comment]
It's not the downloads. Your PC has cached an invalid copy of the EXE. Probably due to the antivirus you were running originally. Glad you got it working though.
