### ISSUE TITLE
Stratum not working

### ISSUE THREAD

**Issue by ryangrimes** [nwoolls/MultiMiner#203]
I have a pool setup that the config is known to work and I have the stratum setup on a Windows VM with the firewall turned off.  I can't get any of my S3's or S4's to connect to the stratum.  They are all on the local network and multiminer sees them and works great with them other than this issue.

Where should I start troubleshooting?

**Comment by ryangrimes** [comment]
Ok, I found the "start" button and I can see hashrate starting to flow through the proxy.  A few minutes into it and I'm not pushing much hashrate (I have 10TH at home going through it) and my miners start beeping.  If I re-direct them back to my other stratum proxy they behave fine.

**Comment by nwoolls** [comment]
Does this occur in BFGMiner alone without MultiMiner? BFGMiner is providing the proxying functionality.

You can test this by stopping mining, bringing up the Process Log, and right-clicking the entry for the Stratum proxy. Click Launch to launch BFGMiner with the same arguments used by MultiMiner.

https://github.com/nwoolls/MultiMiner/wiki/Process-Log#process-log

If the issue persists with only BFGMiner, outside of MultiMiner, I would recommend reporting the issue (including the Arguments from the Process Log) to the BFGMiner repo or thread:

https://github.com/luke-jr/bfgminer/issues
https://bitcointalk.org/?topic=877081

**Comment by nwoolls** [comment]
Closing due to no response - please reopen if issues persist.
