### ISSUE TITLE
Annoying popup

### ISSUE THREAD

**Issue by easye35** [nwoolls/MultiMiner#205]
I changed the ip of my router from 192.168.4.1 to 192.168.1.1.  Now I'm constantly getting a popup saying that my antminers at address 192.168.4.\* aren't responding, but they have been changed to the new router ip.  The app doesn't seem to want to forget about the old ip pool

**Comment by nwoolls** [comment]
Can you please post the details of the popup - e.g. screenshot & copy & paste the error message?

**Comment by easye35** [comment]
![error](https://cloud.githubusercontent.com/assets/11009400/6309648/adc86334-b90c-11e4-8b90-2cc92892a108.jpg)

**Comment by easye35** [comment]
my Ip address is 192.168.0.13

**Comment by nwoolls** [comment]
You can edit the NetworkDevicesConfiguration.xml file found in ~/.config/MultiMiner on Linux and OS X and found in %appdata%\MultiMiner on Windows. Remove the old entries, save, and re-launch MultiMiner.

**Comment by nwoolls** [comment]
Closing issue due to lack of response. Please reopen if issues persist.
