### ISSUE TITLE
Not Showing Gridseed 5-chip devices

### ISSUE THREAD

**Issue by Nick621** [nwoolls/MultiMiner#206]
I've read a lot and love the interface and ease of use but it will not detect any of my 4 Gridseed 5 Blades? CGminer picks them up fine so the drivers are working.

**Comment by nwoolls** [comment]
CGMiner uses different drivers than BFGMiner and MultiMiner. Please check the online help and ensure you have the right drivers installed:

https://github.com/nwoolls/MultiMiner/wiki/Drivers#silicon-labs-usb-to-uart-driver

**Comment by Nick621** [comment]
When I click download it says the file is not there. Can you upload them
again. I need the .INF files for the gridseeds.

------------------------------------------------------
Nicholas Bell
(904)214-5532
------------------------------------------------------

**Comment by nwoolls** [comment]
Sorry about that. Did some cleanup on Dropbox and didn't realize it broke the link. Should be fixed now.
