### ISSUE TITLE
dotNET4

### ISSUE THREAD

**Issue by Robeardley** [nwoolls/MultiMiner#207]
Firstly thanks for an awesome programme,  as a long time photographer / MAC user I don't do command line or code of any sort and I spent a long time failing to replicate VCP on Linux Mint 17 and have now rebuilt in Win7.  My initial mining experiment is a Gridseed 80 chip.

I have installed and un-installed every conceivable permutation of dotNET4 but hitting the Multiminer 4.0.1 .exe simply produces the warning that I need dotNET4 and would I like to download it now.  

Having already installed it both from that link and direct from MS,  hitting NO ends the install and I'm beginning to go a bit nuts.

I have just downloaded the zipped version which opened up ,  installed BFG Miner and seems to be good.  Presumably this also requires dotNET4 to be installed and running?

It would be nice to know what Im doing wrong.

**Comment by nwoolls** [comment]
You can use the zip file if it works. The installer doesn't do anything that the zip file doesn't. For some reason it sounds like the installer isn't detecting .NET 4.0 on your system. I'll have to look into that.

**Comment by Robeardley** [comment]
Many thanks,

The zip file certainly looks OK,  but I was beginning to think it was me.

Just for information its an old Dell Dimension 4700 and I’ve installed the 32bit version of Win7,  all updates are up to date.

My final 2 pieces of testing will be to try Multiminer 4.0 which I downloaded last night followed (if that doesn’t work) by uninstalling dotNet4 and re-installing it in x86 version only.

So far I have only used the MS page to download the dotNET4 x86 x64 multi version Client.

I will let you know.

Thanks again

Rob

**Comment by Robeardley** [comment]
I just tried Multiminer 4.0 exe and it produced the same result,  

The installer points to the same version of dotNET4 that I already have installed and the zip version of Multiminer 4.0.1 has detected my miners and seems to be working fine,  so I don’t see much knowledge gain in taking out dotNET4 and trying the x86 only version.

Obviously as a complete newb that argument may be flawed but the required outcome is test mining and I’m a step closer so reluctant to retrace my steps.

Hope this helps a little bit,  sorry to create a task but happy if it solves a problem.

Very best wishes

Rob

**Comment by Robeardley** [comment]
Good afternoon again,

I do hope I’m not contributing to your stress levels without good cause but I just had an afterthought which I don’t know whether it is relevant or not … but

My antivirus would not allow me to download Multiminer 4.0.1 exe,  said there was an adware threat, sadly I didn’t take note.

So Multiminer 4.0.1 exe was downloaded to a Mac and then transferred via a USB Stick.  Once again the anti virus refused to allow its opening / installation and whipped the whole file away to quarantine.

I then disabled the File Scanner in Avast and that allowed me to transfer the file to the desktop and attempt to open it.

I have no idea if this is ,  “as designed”  or  “broken”,  but felt it was worth sharing.

very best wishes

Rob

**Comment by nwoolls** [comment]
AntiVirus apps tend to flag Bitcoin mining software. There's not much I can do about that unfortunately.

**Comment by nwoolls** [comment]
@Robeardley can you please test this installer for the .NET Framework error:

https://www.dropbox.com/s/k1nz40ksv6xxpk6/MultiMiner-4.0.1.exe?dl=0

**Comment by Robeardley** [comment]
Yes I’m learning this is the case now but didn’t know if it was relevant so thought it may be worth a mention …

**Comment by Robeardley** [comment]
PERFECT.

I suspect you knew that without me testing it,  went straight in without the slightest of hiccups.

I have no idea what you did but I hope it helps a few other installers.

many thanks and very best wishes

Rob

**Comment by nwoolls** [comment]
Fixed in 3ddd4acd1ef98a1ed754787dc92055d1dd559716

**Comment by Robeardley** [comment]
Good evening,

is it possible to have Multiminer Installer without        Win32 Malware gen   [PUP]     ?

The version you Drop Boxed also contained it !

very best wishes

Rob

**Comment by nwoolls** [comment]
As stated before: AntiVirus apps tend to flag Bitcoin mining software. There's not much I can do about that unfortunately.

**Comment by Robeardley** [comment]
I know and I apologise for raising it again but this isn’t just flagging up mining software,  its telling me the installer contains a Potentially Unwanted Program.

I thought your download hub may be adding it which is why I scanned the one you Drop Boxed … and there it is again.

Once detected Avast wipes out Multiminer …

If its there and you meant it to be there and its doing nothing malicious I’ll take your word and run it but I looked it up and I’d rather not have it.

All the very best

Rob

**Comment by nwoolls** [comment]
Any virus or malware flags are false-positives.

**Comment by Robeardley** [comment]
Are you sure Mr Wools he he ?

OK I’m taking your word for it,  it runs quite happily with the file scanner switched off but I hit the “Update” that arrived and the download scanner got it.

many thanks

Rob

**Comment by Robeardley** [comment]
Good afternoon,

just a final thank-you and update that may be helpful.

I blundered into your list of several anti virus scanners and how they report Multiminer.  Five minutes after I moaned to you about it.  very interesting

I then spent many hours attempting to start the miner and just hitting an unhandled exception error.

I’ve seen that many fixes for this and absolutely none of them made any sense to me,  being a none coding noob.

It did occur to me however that I had installed / un-installed MultiMiner about a gazillion times into the same folder and it always remembered my settings.  So I guessed there was a chance the errors were cached as well….

So I have removed every last trace of Multiminer and started again using the .zip version,  boom,  started Bfg Miner,  Firewall didn’t like that,  allowed it and its running ….

There were a few moments where that unhandled exception dialogue nearly caused physical damage.

Million thanks

Rob out

**Comment by Robeardley** [comment]
Good morning,

let me know if I need to raise another thread as I’m not sure of the protocol here … this one having been closed etc.

I spoke too soon the other day,  it worked flawlessly for about 2 hours and I thought all was well.

I had made an error in some of my mining parameters so I stopped mining, made the changes and shut down for the night.

Windows installed some updates whilst shutting down.

Next morning I re-started Multiminer full of confidence and hit START,   only to get the “Unhandled Exception has occurred in your programme”  dialogue …. error box aaaaaarrrrrrrrggggghhhhhh

I have restored to before the windows updates arrived,  no good.  I have un-installed .NETFramework 4.5,  installed v4.5.2,  no good.  Un-installed v4.5.2 and gone back to v4.  No good.  This is driving me insane.

So is the .NET4 unhanded exception thing surmountable in easy steps that I can follow or….

Can i go back to a previous issue of Multiminer that only requires the Win7 natively installed .NET3.5  or

Can you point me to version of Linux that has a natively installed Virtual Com Port driver because Linux Mint 17.1 is fantastic but installing drivers is a complete nightmare.  I notice your install instructions are for DEBIAN and several users have reported that their miners were just detected and went straight in using Debian ?

So fantastic application and I want desperately to use it but I am being prevented at the moment and the wife is beginning to nag about the hours and hours spent Googling a fix …..

Very best wishes

Rob

**Comment by Bleakwise** [comment]
No, they don't report multiminer.

I downloaded the zip and no problem. I download the installer.exe, and McAfee is detecting w/e crap is included in the installer.
