### ISSUE TITLE
stop work when switch user or lock session in win

### ISSUE THREAD

**Issue by Pascal66** [nwoolls/MultiMiner#213]
Each time i switch user, or look my session with password, multiminer stop it's work and restart when i'm back to my session

**Comment by nwoolls** [comment]
Are you GPU mining? If so this is unavoidable.

**Comment by Pascal66** [comment]
Ok that's clear, thank you !
Even with multiminer as windows service ?

**Comment by nwoolls** [comment]
It's not a limitation of MultiMiner. Windows does not allow GPU resources to be consumed by a logged out user. It is the underlying mining software that is stopped by Windows, not MultiMiner itself.
