### ISSUE TITLE
Avira Anti-virus thinks Multiminer is a viris

### ISSUE THREAD

**Issue by Jelks** [nwoolls/MultiMiner#214]
This has been going on for some time, for at least a month (I'm thinking more like two months).

I've been happily using Multiminer since late last July. 4-8 weeks ago, Avira started beeping at me that I had an infected file -- the MM executable. So I removed it, waited a week, downloaded the now latest MM.  It ran for a some hours, then Avira shouted at me again.  I removed it.  This has gone on at least three times.

I did without MM for the last two weeks -- I've got two Antminer S3s that mine on their own.  But I decided I still wanted MM for the collection of USB ASICS I've got that contribute about 70 GH/s to my mining.

So I just downloaded the latest release.  This time, I didn't even have to install the thing, Avira screamed at me as soon as the download was complete on the Windows installer executable!

So if this is a false positive, Avira needs to be alerted and the MM executable needs to be submitted to them for "forensic evidence" so they can clear it and issue their update.

I really like MultiMiner, and I contribute while I'm mining.  But I won't risk a virus, like or no like.  Avira is a popular anti-virus package.  Please clear it with them.

Thank you,

Jelks

**Comment by nwoolls** [comment]
There's not much I can do about this. AntiVirus companies tend to flag mining software as viruses and malware. I am not going to pay to digitally sign the releases as that costs both money and exposes my personal address to anyone who views the certificate details.

You either need to take steps to allow the software to run (by allowing the executable(s) in your antivirus software) or use something else.
