### ISSUE TITLE
Linux equiv of VCP

### ISSUE THREAD

**Issue by Robeardley** [nwoolls/MultiMiner#215]
Good afternoon,
this is not strictly your problem and I understand that but I cannot find the answer anywhere else...

My previous attempt to install multi miner on Linux mint 17.1 was performed before I had the miner plugged in.

Everything worked flawlessly,  running under mono and installing BFG miner etc was no problem,  however as soon as the miner arrived it was impossible to detect it and no amount of jiggery pokery over many days would let it be found or would let me find and install the equivalent of VCP STM32,  so I gave up.

Your Linux install notes specify "Debian", based so my question today is ... "If I install Linux mint Debian edition with the miner plugged in,  will it detect and install the equivalent of VCP that will allow MultiMiner to find the miners on USB ports?

Many thanks
Rob

**Comment by nwoolls** [comment]
@Robeardley please see the following page for which drivers to install on which OS and for which miners:

* https://github.com/nwoolls/MultiMiner/wiki/Drivers
