### ISSUE TITLE
Paycoin pool

### ISSUE THREAD

**Issue by chrishaefner** [nwoolls/MultiMiner#216]
Hi,
So I was trying to plug in a paycoin XPY pool, but I cant seem to get mulitminer to switch over to this new pool config. Any ideas on why? Here is what I am using ( copy and past from my profile on http://xpypool.com)

paycoin multipool
by paycoin australia
X11 Status:
 Hashrate : 146.35 MH/s 
 Active Miners: 17 SHA256 Status:
 Hashrate : 22,240.89 GH/s 
 Active Miners: 50 Scrypt Status:
 Hashrate : 1.26 GH/s 
 Active Miners: 64
  Getting Started
  User Stats
  Pool Stats
  Leaderboard
  Contact Us 
  Language 
×
MYR conversion delayed - 3/15/2015

I've waited as long as I can. MYR has NOT been converted for payouts yet. Will payout ASAP.
×
VARDIFF Starting Difficulty for Big Rigs - 1/14/2015

Big rigs, (1GH/s+ for scrypt, 250MH/s+ X11, or 2TH/s+ SHA) if you use the VARDIFF ports, for your password, please use --diff=### as a starting difficulty where ### is an applicable difficulty. Starting a big rig without this (especially on X11) will result in getting your IP banned. If you have trouble, email us! :) 
We are a PPLNS style pool. For more information on this, please visit this page.
Step 1. Pick the region nearest to you

  New York, New York

URL: stratum.paycoinmultipool.com
Step 2. Pick a port
  US Ports
x11 ports:

Profit Switch:
Port: 4333
Payout Method: pplns
Diff: 0.0009 - 8
2.0% fee
Past 4d Profit: 0.15893432 BTC/GH
 Profit Switch:
Port: 4334
Payout Method: pplns
Diff: 4
2.0% fee
Past 4d Profit: 0.15893432 BTC/GH
sha256 ports:

Profit Switch:
Port: 6333
Payout Method: pplns
Diff: 8 - 8192
1.0% fee
Past 4d Profit: 0.00000900 BTC/GH
 Profit Switch:
Port: 6334
Payout Method: pplns
Diff: 8192
1.0% fee
Past 4d Profit: 0.00000900 BTC/GH
scrypt ports:

Profit Switch:
Port: 3333
Payout Method: pplns
Diff: 8 - 32768
2.0% fee
Past 4d Profit: 0.19019643 BTC/GH
 Profit Switch:
Port: 3334
Payout Method: pplns
Diff: 8192
2.0% fee
Past 4d Profit: 0.19019643 BTC/GH
Step 3. Set a username
Payout currency:
Pick a currency that we pay out in
Payout address:
 Valid XPY address
Step 4. Configure your first worker (optional settings)
Workername:
Alphanumeric characters only
Starting/Static difficulty:
Optional. Specifies a starting difficulty for VARDIFF ports and the desired difficulty on STATIC ports.
Step 5. Configure your miner
URL: stratum.paycoinmultipool.com
Port: 6333
Username: PUTod1pdAQatbgZzdN4j5nfjKzF8jvZfFn.worker1
Password: x
Commandline example: ./sgminer -o stratum+tcp://stratum.paycoinmultipool.com:6333 -u PUTod1pdAQatbgZzdN4j5nfjKzF8jvZfFn.worker1 -p x -I 13
Step 6. Make sure your hashrate shows up
Stats link: http://xpypool.com/stats/PUTod1pdAQatbgZzdN4j5nfjKzF8jvZfFn

After a few minutes of mining your stats page should be showing a graph and hashrate for your miners. If it isn't, double check your configs.

Step 7. Edit your account settings - Under Construction!
Settings link: http://xpypool.com/settings/PUTod1pdAQatbgZzdN4j5nfjKzF8jvZfFn

More configuration of your account is available on your account settings page. Including:
Setting additional payout addresses (this is NOT required! If you leave all the addresses blank, you will get paid in all of the coin address type you are mining with.)
Add a donation to the pool
Enable privacy (hides your address on the leaderboard)

**Comment by nwoolls** [comment]
I have no intention of supporting Paycoin. Not going near that.
