### ISSUE TITLE
Antminer U3 not recognized

### ISSUE THREAD

**Issue by presbyjr** [nwoolls/MultiMiner#217]
I have tried installing my antminer U3 which I can not get it to be recognized.  I have installed the drivers from BITMAIN's website with no luck.  Will an antminer u3 work using multiminer?  Thanks.

**Comment by nwoolls** [comment]
I don't have one to test. I believe the latest version of BFGMiner supports the U3. You can try downloading the latest BFGMiner and then extracting it into the Miners\BFGMiner folder. Let me know if / how that works.

**Comment by presbyjr** [comment]
Thanks for your help.  I think I've got to the point where I will have to
wait to see if you can make that U3 drivers compatible with your software.
By the way I really love your software it is really nice.   Thanks again.

**Comment by nwoolls** [comment]
I'm not sure what you mean - there are no drivers for me to make compatible.

Extract BFGMiner 5.1 into the ```Miners\BFGMiner``` folder and then scan for hardware. You'll need to install the drivers found on the Wiki for the AntMiner USB devices:

https://github.com/nwoolls/MultiMiner/wiki/Drivers#drivers

There's tips for troubleshooting undetected devices here:

https://github.com/nwoolls/MultiMiner/wiki/Local-Devices#local-devices

**Comment by presbyjr** [comment]
According to the bfgminer website, they don't recognize the U3 usb device
yet.  Tried 5.1, no luck.

**Comment by nwoolls** [comment]
Check the thread at bfgminer.com for more info on U3 support. There is a testing branch it seems.

**Comment by presbyjr** [comment]
Ok thanks!!
