### ISSUE TITLE
BFGminer did not install with Multiminer

### ISSUE THREAD

**Issue by jjmikolajcik** [nwoolls/MultiMiner#218]
I am using windows 7 64 bit system and recently downloaded multiminer. While reading I noticed that it was supposed to have downloaded BFGminer automatically to help the program run correctly. I have tried downloading BFGminer on its own but multiminer kills the program upon start up. I am trying to use 2 USB antminers and cannot get multiminer to recognize more than one piece of hardware. I am new to this and trying to follow the information that people have set forth but keep coming up empty.

**Comment by nwoolls** [comment]
You can disable the *Detect orphaned miners* option and MultiMiner will not kill stray mining processes on startup:

https://github.com/nwoolls/MultiMiner/wiki/Settings#miner-settings

**Comment by jjmikolajcik** [comment]
This should then allow BFGminer to run and detect the other antminer that is plugged into the system?

**Comment by nwoolls** [comment]
If you are having trouble with detection of local mining devices, see the following help page:

https://github.com/nwoolls/MultiMiner/wiki/Local-Devices#local-devices

That includes where to find the logs of output returned by BFGMiner.

**Comment by nwoolls** [comment]
Closing pending response, please reopen if you are still facing this issue with the [latest release](downloads.multiminerapp.com) of MultiMiner.
