### ISSUE TITLE
Cannot restore after being minimized

### ISSUE THREAD

**Issue by jakerich** [nwoolls/MultiMiner#219]
I have MultiMiner-4.0.3 installed on Windows 7 Pro 64 Bit. It is set to auto-start at log-in, then minimize to tray. I cannot "show" the application anymore. It was working earlier today, then after a reboot, it will no longer restore to show the app. I can right-click the icon in the tray and select "Show" but all that does is put the icon on my taskbar, it does not show the app so I can make setting changes. I should make sure to note that the app is still running and processing work. I have also un-installed and re-installed the app. This did not change anything and the app remembered all the original settings and still auto-starts and runs minimized.

***Update - I did these steps to do a "real" re-install (this worked):

FAQ

How do I restart the setup wizard? How do I delete all my MultiMiner settings and start over?
Reset settings by deleting the contents of %appdata%\MultiMiner (type that into the address bar in Windows Explorer). Be sure to quit MultiMiner before you delete the contents. Then, restart MultiMiner.

**Comment by nwoolls** [comment]
@NevadaJake let me know if you find a set of steps that gets MultiMiner into this situation again. I'll see if I can reproduce as well.

Glad to know you worked around the issue in the meantime.
