### ISSUE TITLE
Just closes after one second #220

### ISSUE THREAD

**Issue by Philander** [nwoolls/MultiMiner#222]
"Can you try this build?

https://www.dropbox.com/s/qm1h1u2y08r1x6y/MultiMiner-4.0.3.zip?dl=0"

Multiminer just closed on me again.  Then the same thing started happening, closes 1 second after opening.  

The build in the link works perfectly, it does not close/crash right after opening anymore and there was no need to remove and install donet4/4.5 again.  Thanks.

**Comment by nwoolls** [comment]
Is there any information you can share with me about your network interfaces? For instance the output of ```ipconfig /all``` at the command line? If you'd rather share it privately you can send it to nwoolls @ gmail.com.

**Comment by nwoolls** [comment]
Fixed in 9cfffd639e6060258b021d33605353a75464a9da
