### ISSUE TITLE
Cant get controller onto network

### ISSUE THREAD

**Issue by chrishaefner** [nwoolls/MultiMiner#223]
Hi,
I am trying to configure a controller to run on my multiminer network. I tried a raspberry pi ran with minera, but no luck. I have no problem getting everything onto the SD card, but I cant find it on my network monitor.  What is the easiest way to get a controller up and going with multiminer. If I have to get new hardware so be it.

**Comment by nwoolls** [comment]
I'm not sure I follow your question. What is your goal? To monitor a miner already on your network using MultiMiner? Or to use MultiMiner itself on an ARM controller?

**Comment by chrishaefner** [comment]
My goal is to get multiminer onto the controller.

**Comment by nwoolls** [comment]
Please see the following link for instructions on running the MultiMiner TUI on an ARM-based device:

https://github.com/nwoolls/MultiMiner/wiki/Installation#arm-installation-beaglebone-raspberry-pi

**Comment by chrishaefner** [comment]
Thank you.  I'm up and running :-)

**Comment by nwoolls** [comment]
My pleasure - happy mining!

**Comment by chrishaefner** [comment]
Hi nwoolls/MultiMiner,

I'd like to add you to my professional network on LinkedIn.

- Christopher

Confirm that you know Christopher: https://www.linkedin.com/e/v2?e=0-iimsbfbx-wo&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=SoALOdZu&invitationId=6086416734124863488








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iimsbfbx-wo&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGxo-R0zg1KxwAAAVHdL3zixdyx_tWiZRodP29iqWRecNDw2i1yg1dzte6ZLsr38JyFCdlL5ECg6G9iAYWOYJgGi-9LH-k7T42Wr8Xyc0F4UMKFdE-hfYtRMo5savjoEbK08QRc1c3x1pja-lTPSQEDD0GmILtXk5YPN-Md9GF0kaPRC4OxJhDVZErnVM772sFD&eid=0-iimsbfbx-wo


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iimsbfbx-wo&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chrishaefner** [comment]
Hi nwoolls/MultiMiner,

I'd like to add you to my professional network on LinkedIn.

- Christopher

Confirm that you know Christopher: https://www.linkedin.com/e/v2?e=0-iimsbfd0-j0&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=CYZEmcqb&invitationId=6086416734326181888








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iimsbfd0-j0&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFGdFOM5LiqawAAAVHdL3v7O2n-nJvkpWQrdeDNAoYyK9yP0InhmE23dyRWS9UiEwKTqwyr9hNsOCnwBjvE4M1Z_wTZqJPtZ511IA2p0k_3RI92LdXcUmpIJ5Bf0F2k0NRh6Kcu2_v_zE_GgjQ-Gzd1ZDxhl9lhCXDyNwxIgVOHI_EgSk3BrGStUG5pBH1VJ86c&eid=0-iimsbfd0-j0


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iimsbfd0-j0&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chrishaefner** [comment]
Christopher Haefner would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=59mtb5-ij0f2962-ww&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=SoALOdZu&invitationID=6086416734124863488

View Christopher Haefner&#39;s profile: https://www.linkedin.com/e/v2?e=59mtb5-ij0f2962-ww&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=SoALOdZu&invitationID=6086416734124863488





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=59mtb5-ij0f2962-ww&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=59mtb5-ij0f2962-ww&loid=AQH_P03ULleVXwAAAVIO34bxxaRhWz2ggPj_sWYj53XoPQwKB1wt0bYkZBEnyyd1hRfQUI6U1gwPZk7DsYTW9kdx1F85589Eone2a9faCKYkoDHoFEmqezKuidQBzxlKmsxxwzfs2aLYSXZrAlBWPDP36cENwpONJNLFyCVBfOnFTWaQ4QvwIzXXy5fXmtlcCLC3

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=59mtb5-ij0f2962-ww&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chrishaefner** [comment]
Christopher Haefner would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=2250xo-ij0f1z3z-f&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=CYZEmcqb&invitationID=6086416734326181888

View Christopher Haefner&#39;s profile: https://www.linkedin.com/e/v2?e=2250xo-ij0f1z3z-f&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=CYZEmcqb&invitationID=6086416734326181888





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=2250xo-ij0f1z3z-f&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=2250xo-ij0f1z3z-f&loid=AQHV6DIjKZY57wAAAVIO4eF1i_iFGiTXnegpVHQvotQb8bdRllfFsvTPRNI1rsFQtP7-qXaOyWTH2Zjfk58lOTucUaecaNxYPE3Bq7YCapk40oURhsFT7DrO5ZS4mJ8gf3cgB-BgA0oH4BbA33S0SzJrRkEt588gfIdkA4dhgQFZUd-7bjLD1r_QYs1NVcl45fUI

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=2250xo-ij0f1z3z-f&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chrishaefner** [comment]
Christopher Haefner would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=2250xo-ij3ze4pl-2v&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=CYZEmcqb&invitationID=6086416734326181888

View Christopher Haefner&#39;s profile: https://www.linkedin.com/e/v2?e=2250xo-ij3ze4pl-2v&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=CYZEmcqb&invitationID=6086416734326181888





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=2250xo-ij3ze4pl-2v&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=2250xo-ij3ze4pl-2v&loid=AQHolVrafNkAAgAAAVIcLM-3JWWVM3n2iSznn0x7uIsDXKLGVEqQE_CXzVG2fhJKA_wMoYVYp1PuBRYfqkKYoOK2MwUNfSnjqRfxfCkCq_400I0fN0wZ09sFOKLthFUKBkxigboKjnNGrnO0-PEKusCSYFGJeeqRB4Qh7kN9lGW4dyEsX7nih_ePBYeS0zLeobIY

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=2250xo-ij3ze4pl-2v&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chrishaefner** [comment]
Christopher Haefner would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=59mtb5-ij3zgagk-tz&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=SoALOdZu&invitationID=6086416734124863488

View Christopher Haefner&#39;s profile: https://www.linkedin.com/e/v2?e=59mtb5-ij3zgagk-tz&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=SoALOdZu&invitationID=6086416734124863488





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=59mtb5-ij3zgagk-tz&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=59mtb5-ij3zgagk-tz&loid=AQHz--nqohAGcwAAAVIcLWy4stLmI_9bfh-0y4bi18BCevOyCkuxyX55X-0DSh5ge9EDY_CJGjWX3NnBrBHZrIZg5jOgoAd9maUgX7tck4rwMFRXHOcGS0wFCwJQDxMcxLTkZszcK57mt_81upE39nlsTj67jeKXMwRx0JxXdKpssNlbfXj_eOmfemKsnqrGe9al

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=59mtb5-ij3zgagk-tz&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
