### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by kushkush2** [nwoolls/MultiMiner#225]
Everytime I open the login for the dashboard and log in, I get a script error, and then I can't get past the screen that asks which subscription plan you want. Can't click on Free or any of the other buttons. I've removed the URL in case it contains information relevant to me. If you need the screenshot with the full URL let me know.
![capture removed](https://cloud.githubusercontent.com/assets/12114909/7334106/55ff4d76-eb56-11e4-94fb-2df710120926.png)

**Comment by nwoolls** [comment]
Can you please email nate @ mobileminerapp.com with your registered email address if the problem is still occurring?
