### ISSUE TITLE
Custom miner like cudaminer

### ISSUE THREAD

**Issue by GeorgeLubaretsi** [nwoolls/MultiMiner#23]
Can we have ability to add custom miners like cudaminer for Nvidia cards? Maybe just have additional fields to path to miner and miner-specific parameters

**Comment by primehat23** [comment]
I am considering right now building a cuda windows 7 multiminer nivida 970 build. I am looking for BTC for funding.

**Comment by Raginglikeaboss** [comment]
Do it boy.  Make nwoolls proud.
