### ISSUE TITLE
Add Monero Scrypt Support

### ISSUE THREAD

**Issue by omegavladd** [nwoolls/MultiMiner#230]
While I've heard great things about MultiMiner the only mining I actively do is for Monero (XMR).

https://bitcointalk.org/index.php?topic=583449.0

While I would love to try your application out without the support of the scrypt I'm interested in mining I will not have a need for it.

**Comment by nwoolls** [comment]
Any coin and algorithm can be added (by you) as long as there is a CGMiner fork for mining. Please read the docs.

https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms#gpu-algorithms
