### ISSUE TITLE
Antminer S5 not detect 

### ISSUE THREAD

**Issue by toxabay** [nwoolls/MultiMiner#231]
Hi. A have a problem with detect any miner in my farm. 
First, i want to detect antminer s5. log from RPC
./minerpc.sh 10.12.5.77
[SUCCESS] devs RPC call succeeded (STATUS=S returned)
./minerpc.sh: line 30: bc: command not found
./minerpc.sh: line 89: ((: 75 <  &&  < 125 : syntax error: operand expected (error token is "&&  < 125 ")
[FAILURE] hashrate ratio is NOT sane (current=1812078.27 average=1145208.59 ratio=)

multiminer not detect anithing from local network.

**Comment by nwoolls** [comment]
Please see the following:

https://github.com/nwoolls/MultiMiner/wiki/Network-Devices

**Comment by toxabay** [comment]
hi. I have this string in cgminer.conf 
"api-listen" : true,
"api-network" : true,
"api-allow" : "W:0/0",
