### ISSUE TITLE
Enhancement Request: Pool Port Column

### ISSUE THREAD

**Issue by imp0stor** [nwoolls/MultiMiner#233]
I use multiple mining proxies on a single machine for multiple mining pools and user accounts for various peoples miners that I manage. I would like to be able to see the port number in the column list so that I can understand which miners are mining for what users and where.

**Comment by nwoolls** [comment]
Thank you for the suggestion - this option will be available in the next update by clicking the *Pool* column header, similar to the optional display of *Work Utility*.
