### ISSUE TITLE
Feature Request: Add network device manually

### ISSUE THREAD

**Issue by 0xicl33n** [nwoolls/MultiMiner#235]
Ive been  digging through docs for about 10 minutes now trying to see if there is a way to add my network devices manually. The "automatic detection" will absolutely not work for me because i have all my miners on different networks(which already have the subnet setup so i can talk to them from here). 

Im sure i can coax my miners to expose their api to the network ( in fact i just tried), but i just cant see them from multiminer.. This is a huge missing feature imo that should have been taken into consideration already.

**Comment by nwoolls** [comment]
You can edit the file ```NetworkDevicesConfiguration.xml``` in the MultiMiner settings folder (```%appdata%\MultiMiner``` on Windows).

**Comment by 0xicl33n** [comment]
thanks!

**Comment by 0xicl33n** [comment]
what exactly is the format for an entry of a device?

**Comment by nwoolls** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfNetworkDevice xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NetworkDevice>
    <IPAddress>192.168.0.8</IPAddress>
    <Port>4028</Port>
    <Sticky>true</Sticky>
    <Hidden>false</Hidden>
    <RecentCommands />
  </NetworkDevice>
</ArrayOfNetworkDevice>
```
