### ISSUE TITLE
404 Error on dashboard and metrics page

### ISSUE THREAD

**Issue by Ducatel** [nwoolls/MultiMiner#237]
Hi everybody,

The dashboard and the metrics page generate a 404 error on windows 10 x64.

![2015-10-28_11-57-38](https://cloud.githubusercontent.com/assets/1184332/10786548/1880759a-7d6b-11e5-89eb-0f61e3e7bd09.png)

I did something wrong ?
Thanks in advance for your help ;)

**Comment by OutdoorKines** [comment]
Any word on this? I had the same issue today. And no Android app

**Comment by nwoolls** [comment]
MobileMiner was shut down several months ago. You would need to contact the folks at http://cryptoglance.info about the future of the MobileMiner project.

**Comment by OutdoorKines** [comment]
Any word on the original topic. Windows 10 and the Blue Screen of Azure issue?

**Comment by OutdoorKines** [comment]
And I appolgise for the off topic android bit

**Comment by nwoolls** [comment]
It's the same thing - the 404 is because those pages link to MobileMiner. The rest of the app should function as normal.

**Comment by OutdoorKines** [comment]
Ah. ok. As i am just getting into this, is there any timeline on removing those tabs in a future update? The tab locations are prime app realestate

**Comment by nwoolls** [comment]
Not really. I'm not actively mining or working on the app and last I heard the CryptoGlance.info guys were setting MobileMiner back up. You or anyone else is free to submit a Pull Request that makes them optional or hidden until the service is up.

**Comment by OutdoorKines** [comment]
Cool.
