### ISSUE TITLE
Remove MobileMiner References

### ISSUE THREAD

**Issue by Raginglikeaboss** [nwoolls/MultiMiner#238]
MobileMiner was quite frankly amazing, and many of us have managed to jerry-rig our own versions to replace it.

But can we please finally update the main Git and remove all references to it?

I feel as if we're trying to sell a car with only three rubber wheels and one made out of cardboard by still advertising MobileMiner.  (Yes, you may read into my statement.)

**Comment by nwoolls** [comment]
@Raginglikeaboss references have been removed from the software in the latest release. Let me know where else you are seeing links and I'll get them removed.
