### ISSUE TITLE
enhancement request-additional coins

### ISSUE THREAD

**Issue by GatewayDeath** [nwoolls/MultiMiner#241]
if at all possible maybe you could look at a few of the major exchanges and include at least the coins that they support. this would be a good thing to add so that the strategies works for almost all coins available. there are many coins out there and many that are easy to mine and work from the same hashes as others but need different pools. it would be great to be able to have a list of all of these and even have it 'round-robin' them outside of profitability.

**Comment by nwoolls** [comment]
Coins are not built into the app and are not added by updates to the app. They are pulled automatically from the various Coin API's that can be selected and used - CoinWarz by default. You can also use WhatMine, WhatToMine, and CoinChoose. If the coin is there it will show in MultiMiner.

You can also add any coins you want. The dialog on the screen when adding the coin states that it does not need to be in the list. Add the coin, put in the symbol, choose the algo and you should be good to go. 

Note that you can add algorithms too, so there should be nothing stopping you from doing these things.

Please check out the Wiki for more info:

https://github.com/nwoolls/MultiMiner/wiki/Crypto-Coins
https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms
