### ISSUE TITLE
Pool doesn't detect my miner

### ISSUE THREAD

**Issue by isosusi** [nwoolls/MultiMiner#243]
Hello

I'm trying to mine some altcoins with [Multiminer]
I have tried many different pools and always got same problem, pool wont detect my miner.

MultiMiner shows 60 Mh/s but pools always shows 0 h/s

What is wrong?

Thank you
Isosusi

**Comment by nwoolls** [comment]
@isosusi what coin are you mining? 60 Mh/s isn't going to do anything mining Bitcoin at the current difficulty. You need an ASIC.

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
