### ISSUE TITLE
Feathercoin hardfork to Neoscrypt

### ISSUE THREAD

**Issue by HydroMining** [nwoolls/MultiMiner#245]
Hi,

after Feathercoin hardfork to Neoscrypt, when will MultiMiner be updated to support Neoscrypt/Feathercoin in Pools?

Thanks & regards,

Tender

**Comment by nwoolls** [comment]
No need to update MultiMiner - you can already add & modify GPU algorithms along with backend miners.

* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms
* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners
