### ISSUE TITLE
The App Have Some Heavy bad/strange looking

### ISSUE THREAD

**Issue by kingdevil731** [nwoolls/MultiMiner#246]
`Platform: Windows7 32bit

operation	process	file	md5	file type

delete	C:\Windows\explorer.exe (v. 6.1.7601.17514)	C:\Users\Admin\AppData\Local\Microsoft\Windows\WER\ERC\statecache.lock	
	
create	C:\baaife\dybne.exe (v. 0.0.0.0)	C:\Users\Admin\AppData\Local\Temp\is-3U3F6.tmp\dybne.tmp	9303156631ee2436db23827e27337be4.exe

create	C:\Users\Admin\AppData\Local\Temp\is-3U3F6.tmp\dybne.tmp (v. 51.52.0.0)	C:\Users\Admin\AppData\Local\Temp\is-1ENMJ.tmp\_isetup\_shfoldr.dll	92dc6ef532fbb4a5c3201469a5b5eb63.dll

write	C:\baaife\dybne.exe (v. 0.0.0.0)	C:\Users\Admin\AppData\Local\Temp\is-3U3F6.tmp\dybne.tmp	9303156631ee2436db23827e27337be4.exe

write	C:\Users\Admin\AppData\Local\Temp\is-3U3F6.tmp\dybne.tmp (v. 51.52.0.0)	C:\Users\Admin\AppData\Local\Temp\is-1ENMJ.tmp\_isetup\_shfoldr.dll	92dc6ef532fbb4a5c3201469a5b5eb63.dll
`

further more here is a full scan :100: [https://sandbox.deepviz.com/report/hash/a4d007f92aa456e6896868705e9d10b0/](url)
and besides there is 17 detected in  VirusTotal ( though i understand it some may be false positive)
So I don't think it's friendly XD

**Comment by nwoolls** [comment]
Virus scanners report false positives for Bitcoin mining software.
