### ISSUE TITLE
not detecting multiple asic devices (litecoin)

### ISSUE THREAD

**Issue by gbridges96** [nwoolls/MultiMiner#249]
having trouble getting it to recognize the following: 1 zeus gaw miner, 2 ltek dragon usb miners , a zeus 18-20 mhs (x3 somthing idk name exactly) . i dont understand why the gaw miner isnt showing up considering i have 5 that do. need drastic help new to mining with hardware

**Comment by nwoolls** [comment]
@gbridges96 make sure you are using a powered hub if some devices show but not others.

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
