### ISSUE TITLE
MultiMiner doesn't detect my GPU

### ISSUE THREAD

**Issue by donadolf24** [nwoolls/MultiMiner#251]
Greetings everywhone! Im using a Geforce 970M GPU but whenver i open up MultiMiner it shows: "opencl" and doesn't display the GPU im currently using. Is there any way to enable it on MultiMiner.
Btw im using a laptop not a PC
not sure if this is the case

**Comment by nwoolls** [comment]
@donadolf24 "opencl" is what your current GPU will show up as. You can rename it if you like using the UI (slow double-click).
