### ISSUE TITLE
Domain expired

### ISSUE THREAD

**Issue by stefanosirplay** [nwoolls/MultiMiner#254]
When i click on dashboard tel me the domain is expired: mobileminerapp.com

**Comment by nwoolls** [comment]
MobileMiner was shuttered a couple of years ago.

**Comment by stefanosirplay** [comment]
Is possible remove a link to mobileminerapp.com from the MultiMiner?

**Comment by nwoolls** [comment]
It's an Open Source project - you are free to remove it and submit a PR.
