### ISSUE TITLE
"Sequence contains no matching element" error when going through Getting Started wizard

### ISSUE THREAD

**Issue by bitmania** [nwoolls/MultiMiner#255]
Installed MultiMiner-4.04.exe from https://github.com/nwoolls/MultiMiner/releases.
Went thru the Getting Started wizard, fill out pool server, worker name, password and click Continue, got the following error:

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at MultiMiner.Win.Forms.WizardForm.CreateEngineConfiguration() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\WizardForm.cs:line 327
   at MultiMiner.Win.Forms.WizardForm.CreateConfigurations(Engine& engineConfiguration, Application& applicationConfiguraion, Perks& perksConfiguration) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\WizardForm.cs:line 282
   at MultiMiner.Win.Forms.MinerForm.CheckAndShowGettingStarted() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2513
   at MultiMiner.Win.Forms.MinerForm.SetupApplication() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2149
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MultiMiner.Engine
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Engine.DLL
----------------------------------------
MultiMiner.Utility
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Utility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MultiMiner.CoinApi
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.CoinApi.DLL
----------------------------------------
MultiMiner.Xgminer.Api
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Xgminer.Api.DLL
----------------------------------------
MultiMiner.Xgminer
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Xgminer.DLL
----------------------------------------
MultiMiner.MobileMiner
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.MobileMiner.DLL
----------------------------------------
MultiMiner.Discovery
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Discovery.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
MultiMiner.Remoting
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Remoting.DLL
----------------------------------------
MultiMiner.CoinWarz
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.CoinWarz.DLL
----------------------------------------
MultiMiner.CoinChoose
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.CoinChoose.DLL
----------------------------------------
MultiMiner.WhatMine
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.WhatMine.DLL
----------------------------------------
MultiMiner.WhatToMine
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.WhatToMine.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.MultipoolApi
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.MultipoolApi.DLL
----------------------------------------
MultiMiner.NiceHash
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.NiceHash.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
MultiMiner.ExchangeApi
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
    CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.ExchangeApi.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Netzarim** [comment]
I am also getting this error... just started recently... Probably due to an MS patch.

**Comment by nwoolls** [comment]
@bitmania @Netzarim this was due to Coinchoose API going offline. This will be fixed in the next update. Thanks for reporting this.
