### ISSUE TITLE
Can't find zeus thunder x6

### ISSUE THREAD

**Issue by victorsledge** [nwoolls/MultiMiner#257]
I have all the correct drivers...at least I think I do. However when I scan it will locate my other zeus miner but not my thunder.

**Comment by nwoolls** [comment]
@victorsledge please send an email to nwoolls at gmail.com if you are able to provide remote access to troubleshoot this issue.

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
