### ISSUE TITLE
File does not contain a valid CIL image

### ISSUE THREAD

**Issue by stovetop121** [nwoolls/MultiMiner#261]
Running Neon (Debian base) on a laptop and Lubuntu on a lower spec tower.

I have followed all the instructions and yet I get the same error no matter which machine I run this on.
"File does not contain a valid CIL image"
I am executing the "exe" file from the releases page. I have tried to move backwards as far as 3.8.5 with the same result.

I can compile and run my own mono programs without this error. The instructions on this site tell me to download "the" zip file on the releases page. But the only two zip files are the Mac version and the source. Just to cover my bases, I downloaded these and found no executable in them.

Any help would be appreciated.

**Comment by nwoolls** [comment]
> The instructions on this site tell me to download "the" zip file on the releases page. But the only two zip files are the Mac version and the source.

That is not the case. There is a zip file for binaries as well. Ensure that is what you downloaded.

> MultiMiner-4.0.4.app.zip
> MultiMiner-4.0.4.exe
> MultiMiner-4.0.4.zip
> Source code (zip)
> Source code (tar.gz)

The direct link is:

* https://github.com/nwoolls/MultiMiner/releases/download/v4.0.4/MultiMiner-4.0.4.zip
