### ISSUE TITLE
Multiminer not detecting usb miner

### ISSUE THREAD

**Issue by Sab1735** [nwoolls/MultiMiner#262]
Hi

I have a antminer u1 attached. It was working fine but since I added the scrypt 220k usb, mulitminer started to play up.
it stopped recognising the antminer u1, and didn't detect the 220k usb either.

I have updated the multiminer app to v4.04, still not detecting either of the usb's connected.

I have tried to disconnect both usbs and connected u1, scanned for device, nothing.

I then disconnected u1 and connected 200k usb, scanne for device, nothing.

I connected both and again nothing.

**Comment by Sab1735** [comment]
i took the 220k usb out and reinstalled the driver CP210x driver. Its working.  Thanks

there is an issue with the 220k usb , when i run the LKController program it came with, it scans for devices. it then throws an error 'unexpected error command line arguments'.

**Comment by multiminer2001** [comment]
remove antminer and drivers try loading 220k usb  and drivers on its own
some miner won't run or play up had simalar problem with a few sha 256
usb miner   like my antminers u1, bit fury red twin chip, nano fury
,butterfly labs 9 gh\s -60gh\s all would play up when tring to set up grid
seed 5 chip dual miners

**Comment by Sab1735** [comment]
<img width="590" alt="multiminer error" src="https://cloud.githubusercontent.com/assets/27373176/25231605/5dd48da2-25d0-11e7-8c2b-d134bb1aa518.PNG">

**Comment by Sab1735** [comment]
i am getting the above error when i start the mining.

**Comment by nwoolls** [comment]
@Sab1735 please click *Details* and copy & paste the full output.

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
