### ISSUE TITLE
I need way to reset config and load wizard again

### ISSUE THREAD

**Issue by wellington1993** [nwoolls/MultiMiner#265]
Hi,

I've installed the multiminer before.
But after remove folder and unzip again the configuration appears still the same.

I want to load Wizard again. Have you any idea to clear actual configuration and reload the Wizard?.

I'm Linux user.
Thanks

**Comment by nwoolls** [comment]
@wellington1993 check for a MultiMiner folder in `~/.config`

**Comment by wellington1993** [comment]
@nwoolls Thats is! Thanks!

**Comment by wellington1993** [comment]
Thanks!
