### ISSUE TITLE
Suggestion: ETHash algorithm support

### ISSUE THREAD

**Issue by mascondante** [nwoolls/MultiMiner#267]
Given Ethereum is the newest and hottest thing (yet the mining software is behind) a great way for this project to shine might be to integrate [cpp-ethereum](https://github.com/genoil/cpp-ethereum). The coin wasn't that popular until recently considering the exchange rate wasn't very impressive. Now that a extreme spike in price has happened I would assume people are itching for a project like this that has an intelligent GUI. Plus if you can get the tip jar working for this coin that would profitable. Let me know what you think.

Thanks!

**Comment by nwoolls** [comment]
You can already add algorithms via configuration:

* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms

**Comment by mascondante** [comment]
What I mean is to release support by default in the next release and advertising it. Asking for a fork of their code to optimize if necessary and merge is just icing on the cake.

**Comment by nwoolls** [comment]
As long as you use the SGMiner fork for ethash it should already be possible using the customizable backend miners and GPU algorithms. I do not have access to a rig capable of mining ETH these days (seems to require a GPU w/ 2GB of RAM) or I'd have already put together and out-of-the-box config.

Please see the following topics for steps that should work:

* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners
* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms

If you'd like to provide secure access to a mining rig or the working config from setting this up I can get a config for this baked in.

**Comment by nwoolls** [comment]
@mascondante version 4.2 is out and has support for Monero (CryptoNight) and Ethereum (Ethash) mining out-of-the-box.

* https://github.com/nwoolls/MultiMiner/releases/tag/v4.2.0
