### ISSUE TITLE
mining good but do not see accepted mining

### ISSUE THREAD

**Issue by rarcntv** [nwoolls/MultiMiner#268]
Hi, 
I am trying to mining with https://www.multipool.us/ . it is connected successfully but I do not see any activity. also accepted details etc.
when I can see it? or how I understand it is working or not? Please check the screenshot.
![problem_for_pooling](https://user-images.githubusercontent.com/1826388/27775156-1a8997ec-5fc1-11e7-8425-5518c8c009e6.jpg)

**Comment by LaMuerteMRT** [comment]
tengo el mismo problema pero el autor cerro mi caso y me derivo a una guia que no me sirvio :(

**Comment by nwoolls** [comment]
@rarcntv you aren't getting any accepted shares because you are mining SHA256 with only 23 Mh/s. That isn't going to find anything at current difficulties.
