### ISSUE TITLE
Navigating to Dashboard throws a Trojan!

### ISSUE THREAD

**Issue by Pcenginefx** [nwoolls/MultiMiner#270]
Just installed MultiMiner on Windows and if you navigate to the Dashboard, it instantly throws a "SupportScam:JS/TechBrolo.AA" trojan alert in Windows 10 as well as pop-up windows saying that your machine has been hacked. Luckily Windows Defender caught it and I was able to close MultiMiner but this is a SERIOUS issue that needs to be fixed before anyone comes close to this app!

**Comment by nwoolls** [comment]
@Pcenginefx thanks for the heads-up. This was left in as another company / developer was meant to pick up the paid / hosted services, but that never happened. If I verify that someone else is squatting this will malware now I'll get an update up that removes the MobileMiner bits.

**Comment by Pcenginefx** [comment]
Thanks - this really freaked me out :|

**Comment by nwoolls** [comment]
This is addressed in the latest release.
