### ISSUE TITLE
Dagger Hashimoto support

### ISSUE THREAD

**Issue by coinsinternet** [nwoolls/MultiMiner#271]
Hi,
I am trying to use different Algorithms like Dagger Hashimoto , CryptoNight or H11Ghost , but looks like MultiMiner does not supports them.
How we can add those?

**Comment by nwoolls** [comment]
Check the Wiki, specifically:

* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms

**Comment by nwoolls** [comment]
If a different Backend Miner is required, see:

* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners

**Comment by coinsinternet** [comment]
Hi,
I really appreciate you answers, I saw this instruction before my ticket, but when I try to add, there is only ability to add a : - Name  and Kernel arguments.  I don't  see how will import the whole algoritm?

![multiminer_error](https://user-images.githubusercontent.com/30026770/28025675-505d0ecc-6551-11e7-8668-3e7f07cc0397.JPG)

What do I miss?

**Comment by nwoolls** [comment]
@coinsinternet my second comment links to where you can add new [Backend Miners](https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners). Every algo comes down to being an argument passed to one of the Backend Miners you have installed & configured.

So if you had a miner `cool.exe` that you use to mine this algo by passing in `-myalgo`, you would add the Backend Miner entry for `cool.exe`, then add an algo by giving it a name, selecting that value from the Miner dropdown, and specify the kernel argument `-myalgo`.

**Comment by nwoolls** [comment]
@coinsinternet version 4.2 is out and has support for Monero (CryptoNight) and Ethereum (Ethash) mining out-of-the-box.

* https://github.com/nwoolls/MultiMiner/releases/tag/v4.2.0
