### ISSUE TITLE
just-in-time (JIT) debugging instead of this dialog box.

### ISSUE THREAD

**Issue by coinsinternet** [nwoolls/MultiMiner#272]
Everytime, when I am starting the software under Windows , even on different machines I got:

Unhandled exception has occured....

just-in-time (JIT) debugging instead of this dialog box.

**Comment by nwoolls** [comment]
@coinsinternet please post the full output of the error, not an abbreviated version.

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
