### ISSUE TITLE
Settings do not save

### ISSUE THREAD

**Issue by WebDeveloperAndrew** [nwoolls/MultiMiner#273]
Whenever I go into my settings and configure miner settings I change the settings to what I want, but as soon as I press OK the settings are reset to default, this happens at every level of the settings

**Comment by nwoolls** [comment]
@WebDeveloperAndrew can you try deleting your existing settings folder and using the latest release afterward? If the problem persists, please let me know your OS.

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
