### ISSUE TITLE
Multiminer can't find BFGminer

### ISSUE THREAD

**Issue by Lady-Nauriel** [nwoolls/MultiMiner#274]
When I installed Multiminer, it did not automatically install BFGminer. I have 4 versions of BFG already installed, but I went through the steps and downloaded the exact version recommended by MM, and put it in a multiminer\miners folder. It still claims there is no BFG installed. What do I need to do to get it to recognize that there is a BFG there?

I'm using Windows 8.

(Please be specific. I'm a hardware person. The software side is all gibberish to me.)

**Comment by Delta691150** [comment]
opened July 15 now Nov 30 and I am the first comment,  not sure if adding that I have the same problem is going to do anything but...

I am using windows 10. 

 I sent a contact msg to Github and they responded with this,
I'm sorry, but you've reached Support for GitHub. It sounds like you may have been looking for support for a specific project that is hosted on GitHub.

https://github.com/nwoolls/MultiMiner

We didn't build that project, so we're not able to support it.

when clicking the link it sends me back to the same place i found to make contact in the first place.

**Comment by iLuvLinux** [comment]
You went to GitHub support? Thats for help with the WHOLE of GitHub. There is thousands of projects on GitHub.

GitHub.com hosts repos/projects like these.

If you want to file an issue, go to https://github.com/nwoolls/MultiMiner 
and click on 'issues', then 'new issue'. People like me will help you resolve these problems.

And, @Lady-Nauriel What version are you using?

**Comment by nwoolls** [comment]
@Lady-Nauriel it's very likely that you have Antivirus that is deleting any miner installations after the download / extract / etc is completed. Even Microsoft's Windows Defender is blocking crypto miners pretty heavily now. It's the nature of the beast unfortunately. There's a lot of malware that packages up the same mining software. You'll need to disable any antivirus and antimalware, then either let MultiMiner download BFGMiner or download it yourself and extract it to `<path to>\MultiMiner\Miners\BFGMiner\`.  Afterward, the following file should exist: `<path to>\MultiMiner\Miners\BFGMiner\bfgminer.exe`.

**Comment by armenma15** [comment]
I tried coping bfgminer.exe under the specified path and it does not work. does anyone know a confirmed working solution?

**Comment by grimereaper666** [comment]
I have BFGMiner under Multiminer/Miners/BFGMiner.
Now thinking problem is WinZip put multiminer under: Multiminer/Multiminer.app/contents/resources.
Multiminer still will not see BFGMiner, and the dent in my desk from my forehead is starting to challenge the desk structure soundness.
Help?
