### ISSUE TITLE
File does not contain a valid CIL image.

### ISSUE THREAD

**Issue by SERHYG** [nwoolls/MultiMiner#285]
hello and thank you for the support.

try to install your error but I could not
I get that error: File does not contain a valid CIL image.
I also clarified that I did not find the executable MultiMiner.Win.exe
if I found in this path MultiMiner-4.1.1/Installer/Launcher/MultiMiner.Win
It is the only thing that gave me problems that I can not solve and I do not even know where to start.
thanks for your help

**Comment by SERHYG** [comment]
ok i found the solution
The acrhivo that you have to download is the one that says app.
and the patch is: MultiMiner.app/Contents/Resources/: mono MultiMiner.Win.exe
I do not get to install it completely because I have to go to work, but back

**Comment by nwoolls** [comment]
If this is Windows download the *.exe* installer - sounds like you first downloaded the source and then the macOS `.app`.
