### ISSUE TITLE
MultiMiner no hash rate on nicehash

### ISSUE THREAD

**Issue by proniss** [nwoolls/MultiMiner#286]
Im trying to mine bitcoins with my 2 BFL Jalapeno ASIC miners on the NiceHash pool, It says a worker is connected but its not showing any hashrate. The hashrate in MultiMiner is working fine and as far as i can tell everything is configured correctly.

**Comment by SERHYG** [comment]
Hi 
how did you configure it?

**Comment by proniss** [comment]
![settings](https://user-images.githubusercontent.com/33498338/32587534-c7b40928-c4bd-11e7-8b3f-406a5eb07042.png)

is this what you mean?

**Comment by proniss** [comment]
still not working...

**Comment by LaMuerteMRT** [comment]
neither in minegarte
![a7d79fb9c1041f28703219bb5ac0b9a5](https://user-images.githubusercontent.com/13895945/34343130-c8b7a5a6-e9c4-11e7-9f4c-f7a02f826038.png)

**Comment by nwoolls** [comment]
Try using the *Process Log* screen to launch the *Backend Miner* directly (stop mining in MultiMiner first). If the issue persists, contact the author of the *Backend Miner* in question.

* https://github.com/nwoolls/MultiMiner/wiki/Process-Log
* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners

**Comment by nwoolls** [comment]
For mining on NiceHash or other "multi" pools, make sure you are using their guide for configuring BFGMiner. Check the MultiMiner help for passing additional args to the Backend Miner:

* https://www.nicehash.com/asic-mining

Specifically - ensure you are using `#xnsub` in the pool URL or click the *Features* button in MultiMiner and click *Extra-nonce Subscribe*.
