### ISSUE TITLE
INVALID SHARES

### ISSUE THREAD

**Issue by poison15ivy** [nwoolls/MultiMiner#287]
Since I started using MultiMiner, there is over 10% of Invalid shares, 90% of the time it is showing in interface speed of 50-300 Kh/s and in fact I am getting "worker offline" and 0.0 h/s reported hashrate and every so often a NEW INVAID SHARE - currently 10 of them 

Reported speed 0.0 kH/s | 24h avg 12.5 kH/s | Total Shares in a month 87,008 | Stale shares 96 (0.11%) | Invalid shares 10 (0.05%)

ASICs are working about 100 kH/s while real speed is when using cmd without any oc 300 or even 1 has its speed in MH/s and here poorly 200 kH/s ... 
too many issues

**Comment by poison15ivy** [comment]
CPU is not even possible to use for mining purposes and when using control panel I get quite significant speeds, also nVIDIA cards are not automatically recognized

**Comment by poison15ivy** [comment]
This MultiCrap has more invalid shares than normal ... Invalid are up to 20 now and even 24 speed is now 0.0 Total shares went up BY ONLY ONE GOOD SHARE !!!

**Comment by nwoolls** [comment]
This has nothing to do with MultiMiner - this is feedback for whatever backend miner you are using (BFGMiner, CGMiner, SGMiner, etc).

You can try launching these individually from the [Process Log](https://github.com/nwoolls/MultiMiner/wiki/Process-Log) screen. You should see the same performance with or without MultiMiner.

**Comment by nwoolls** [comment]
Closing due to lack of response. Please reopen if issues persist.
