### ISSUE TITLE
v4.1.0 broken after copy

### ISSUE THREAD

**Issue by Dycast** [nwoolls/MultiMiner#288]
Hey, just got the newest ver. was setting up a site that has multiple coins so I hit the copy button on one since I only need to change 1 param to switch to different coin, soon as I did got a .NET framework unhandled exception 'sequence contains more than one matching element' re-occuring popup Continue or Quit - same with relaunch, I haven't found where your storing the info for servers/coins, but easy to recreate, just copy one.. Guessing something was just overlooked, would of copied the exact msg. but it's on my other 'puter.. 

Keep up the good work! Best GUI miner I've found

**Comment by nwoolls** [comment]
What OS? Under Windows settings are in `%appdata%/MultiMiner` and under Linux and OS X it's under `~/.config/MultiMiner`.

**Comment by nwoolls** [comment]
Closing due to lack of response - please reopen if the issue persists.
