### ISSUE TITLE
Antminer S9 support

### ISSUE THREAD

**Issue by SyDemo** [nwoolls/MultiMiner#290]
Hello. Is it possible to use the multiminer with the Antminer s9?
When I try to use script rpc-api-test.sh on S9, the answer is FAILURE: devs RPC call failed (STATUS=E returned). Why? Where is my problem?

**Comment by nwoolls** [comment]
Try checking online for how to enable RPC API with the S9. I don't have one to try myself.

e.g.: https://bitcointalk.org/index.php?topic=1525451.0

**Comment by SyDemo** [comment]
RPC API is enabled. Other software successfully connecting and work with S9.

**Comment by nwoolls** [comment]
@SyDemo unfortunately I cannot say without access to a test system. MultiMiner just consumes the standard CGMiner / BFGMiner RPC and has worked fine with miners (that I know of) until now. Works fine with other AntMiners.

**Comment by kalid001** [comment]
New original Bitmain Antminer S9 cost 1000usd


Antminer D3+ 504MH/s Litecoin Scrypt Miner with PSU cost 1,500USD


L3 Specifications:

1. Hash Rate: 504MH/S

2. Power Consumption:800W + 7% (at the wall, with APW3 ,93% efficiency, 25C ambient temp)

3. Power Efficiency: 1.6J/MH + 10%(at the wall, with APW3 93% efficiency, 25°C ambient temp)

Serious buyer should contact us.

Company: Sunway LTD

Email: kalamkean@gmail.com

Whatsapp CHAT or Call : +19842085304 or 0019842085304

**Comment by zaphbee** [comment]
Hello, any updates on this? I have just pludded in my S9. i can log into it through the network but multminer isnt detecting it. 
running latest version on windows 10

**Comment by nwoolls** [comment]
@zaphbee no update - I have no access to an S9 for testing. If you can provide TeamViewer, VNC or RDP access to a network & PC where I can test things send me an email at nwoolls @ gmail.com to schedule.

**Comment by zaphbee** [comment]
This is a better anydesk to use 

910057133

**Comment by nwoolls** [comment]
Unfortunately I do not think MultiMiner will be able to monitor the AntMiner S9 with the current BMMiner provided by Bitmain. MultiMiner uses the `devs` and `devdetails` API commands to get information about the mining devices and BMMiner returns no information for these.

If you'd like to see support for the S9 in MultiMiner I'd recommend reaching out to Bitmain about the lack of support for the `devs` and `devdetails` API commands in their CGMiner fork.

**Comment by JayKayJK** [comment]
Hi, Is it possible that you can add the usage of the `stats` API command to get the chip temperatures?

**Comment by JayKayJK** [comment]
[ApiReport.txt](https://github.com/nwoolls/MultiMiner/files/1684137/ApiReport.txt)

seems that the `devs `command can return something based on the log i have attached from another miner monitoring tool. Hope this helps.

**Comment by nwoolls** [comment]
@JayKayJK it returns with the message `No` instead of any actual device information:

```
API command: devs
{
  "STATUS": [
    {
      "STATUS": "E",
      "When": 1517454313,
      "Code": 10,
      "Msg": "No ",
      "Description": "bmminer 1.0.0"
    }
  ],
  "id": 1
}
```

**Comment by JayKayJK** [comment]
Yes, but it does return the chip temperatures with the `stats `command

> API command: stats
{"STATUS":[{"STATUS":"S","When":1517454313,"Code":70,"Msg":"BMMiner stats","Description":"bmminer 1.0.0"}],"STATS":[{"BMMiner":"2.0.0","Miner":"16.8.1.3","CompileTime":"Fri Nov 17 17:37:49 CST 2017","Type":"Antminer S9"}{"STATS":0,"ID":"BC50","Elapsed":216966,"Calls":0,"Wait":0.000000,"Max":0.000000,"Min":99999999.000000,"GHS 5s":"14046.04","GHS av":14018.80,"miner_count":3,"frequency":"656","fan_num":2,"fan1":0,"fan2":0,"fan3":6000,"fan4":0,"fan5":0,"fan6":5640,"fan7":0,"fan8":0,"temp_num":3,"temp1":0,"temp2":0,"temp3":0,"temp4":0,"temp5":0,"temp6":74,"temp7":72,"temp8":71,"temp9":0,"temp10":0,"temp11":0,"temp12":0,"temp13":0,"temp14":0,"temp15":0,"temp16":0,"temp2_1":0,"temp2_2":0,"temp2_3":0,"temp2_4":0,"temp2_5":0,"temp2_6":89,"temp2_7":87,"temp2_8":86,"temp2_9":0,"temp2_10":0,"temp2_11":0,"temp2_12":0,"temp2_13":0,"temp2_14":0,"temp2_15":0,"temp2_16":0,"temp3_1":0,"temp3_2":0,"temp3_3":0,"temp3_4":0,"temp3_5":0,"temp3_6":0,"temp3_7":0,"temp3_8":0,"temp3_9":0,"temp3_10":0,"temp3_11":0,"temp3_12":0,"temp3_13":0,"temp3_14":0,"temp3_15":0,"temp3_16":0,"freq_avg1":0.00,"freq_avg2":0.00,"freq_avg3":0.00,"freq_avg4":0.00,"freq_avg5":0.00,"freq_avg6":656.00,"freq_avg7":655.52,"freq_avg8":650.00,"freq_avg9":0.00,"freq_avg10":0.00,"freq_avg11":0.00,"freq_avg12":0.00,"freq_avg13":0.00,"freq_avg14":0.00,"freq_avg15":0.00,"freq_avg16":0.00,"total_rateideal":14001.76,"total_freqavg":653.84,"total_acn":189,"total_rate":14046.04,"chain_rateideal1":0.00,"chain_rateideal2":0.00,"chain_rateideal3":0.00,"chain_rateideal4":0.00,"chain_rateideal5":0.00,"chain_rateideal6":4666.12,"chain_rateideal7":4667.33,"chain_rateideal8":4668.30,"chain_rateideal9":0.00,"chain_rateideal10":0.00,"chain_rateideal11":0.00,"chain_rateideal12":0.00,"chain_rateideal13":0.00,"chain_rateideal14":0.00,"chain_rateideal15":0.00,"chain_rateideal16":0.00,"temp_max":74,"Device Hardware%":0.0003,"no_matching_work":2266,"chain_acn1":0,"chain_acn2":0,"chain_acn3":0,"chain_acn4":0,"chain_acn5":0,"chain_acn6":63,"chain_acn7":63,"chain_acn8":63,"chain_acn9":0,"chain_acn10":0,"chain_acn11":0,"chain_acn12":0,"chain_acn13":0,"chain_acn14":0,"chain_acn15":0,"chain_acn16":0,"chain_acs1":"","chain_acs2":"","chain_acs3":"","chain_acs4":"","chain_acs5":"","chain_acs6":" oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo ooooooo","chain_acs7":" oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo ooooooo","chain_acs8":" oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo oooooooo ooooooo","chain_acs9":"","chain_acs10":"","chain_acs11":"","chain_acs12":"","chain_acs13":"","chain_acs14":"","chain_acs15":"","chain_acs16":"","chain_hw1":0,"chain_hw2":0,"chain_hw3":0,"chain_hw4":0,"chain_hw5":0,"chain_hw6":2146,"chain_hw7":20,"chain_hw8":100,"chain_hw9":0,"chain_hw10":0,"chain_hw11":0,"chain_hw12":0,"chain_hw13":0,"chain_hw14":0,"chain_hw15":0,"chain_hw16":0,"chain_rate1":"","chain_rate2":"","chain_rate3":"","chain_rate4":"","chain_rate5":"","chain_rate6":"4681.90","chain_rate7":"4697.22","chain_rate8":"4666.92","chain_rate9":"","chain_rate10":"","chain_rate11":"","chain_rate12":"","chain_rate13":"","chain_rate14":"","chain_rate15":"","chain_rate16":"","chain_xtime6":"{X9=1}","chain_xtime7":"{}","chain_xtime8":"{}","chain_offside_6":"0","chain_offside_7":"0","chain_offside_8":"0","chain_opencore_6":"1","chain_opencore_7":"1","chain_opencore_8":"1","miner_version":"16.8.1.3","miner_id":"8018742c6880881c"}],"id":1}

**Comment by nwoolls** [comment]
@JayKayJK Network Devices that do not return information for the `devs` command are not supported. At this time that includes the S9. This is similar to the older BTC Gardens units:

* https://github.com/nwoolls/MultiMiner/wiki/Network-Devices#btc-gardens

**Comment by JayKayJK** [comment]
@nwoolls Alright. Thanks for the explanation. Any ideas whether they will be supported anytime soon?

**Comment by jamal0077** [comment]
New original Antminer S9 14TH/s + PSU 1600W APW3++ Bitcoin ASIC Miner cost 1000usd
 
New 2018 Hot sale Baikal Giant B with PSU Dash Coin Miner cost 4000USD

Antminer D3 cost $1,100 each unit including PSU and delivery to your home address.

Baikal giant 10 2000usd each unit including PSU and delivery to your home address.

Antminer A3 840 3000USDeach unit including PSU and delivery to your home address.

Antminer L3+ cost $900 each unit including PSU and delivery to your home address.

Delivery takes just 2-3 daysto your home doorstep through FedEx,Ups or Dhl shipping courier services.

We accept payment through Western Union or Money Gram Transfer and also Bank transfer and BTC .

IF YOU ARE READY TO PLACE ORDER AND FOR QUICK REPONSE CONTACT US HERE:

Whatsapp CHAT or Call : +19842085304

Email: james.steven102@engineer.com

Skype: faisa.hassan102

Best Regards


CEO

**Comment by Jubsika** [comment]
Hello, 
Can you tell me how to use API?
Fist as i know I need port which I will connect with API. Where Can I see it?
I also saw network.conf file but there is only ip adresses
Also API access is W:0/0

I'm trying use port 17790 as i saw in google.
for example I'm trying run http://192.168.x.x/17790/api/miners in my browser, but nothing happened. 

Can u tell me what is a incorrect except port? also where i can see port?

Thank you

**Comment by nwoolls** [comment]
The S9 is not supported unless / until BMMiner responds to the `DEVS` API command appropriately:

* https://github.com/nwoolls/MultiMiner/wiki/Network-Devices#antminer-s9
