### ISSUE TITLE
Windows 10 Defender sees CoinMiner trojan in MultiMiner-4.1.1.exe

### ISSUE THREAD

**Issue by nikky2017** [nwoolls/MultiMiner#292]
![coinminer_trojan_screenshot from 2017-11-15 05-21-16](https://user-images.githubusercontent.com/33679655/32820222-21abda8a-c9c5-11e7-845f-48bddda81884.png)

CoinMiner trojan -- feature or threat ?

**Comment by nwoolls** [comment]
Please see other closed issues - most crypto mining software is flagged as malware by AV. Because malware authors ship trojan miners.
