### ISSUE TITLE
Duplicate of #291 - MultiMiner-4.1.1.app.zip is corrupt 

### ISSUE THREAD

**Issue by qcha0s** [nwoolls/MultiMiner#293]
Since you don't bother looking for root cause before closing your issues ... I'll open a new one. 

MultiMiner-4.1.1.app.zip is corrupt 
![screen shot 2017-11-15 at 8 15 20 am](https://user-images.githubusercontent.com/717986/32838268-5829f09c-c9de-11e7-9487-4406588b18dd.png)
<img width="977" alt="screen shot 2017-11-15 at 8 18 25 am" src="https://user-images.githubusercontent.com/717986/32838272-5abf9104-c9de-11e7-8ca0-22dfe6ba718f.png">

**Comment by qcha0s** [comment]
Firefox, Chrome & Safari have all been used. So have multiple unarchive tools. It's only your zip that doesn't open ... i'm gonna go with, it's you, not me.

**Comment by nwoolls** [comment]
@qcha0s good luck with that.

**Comment by nwoolls** [comment]
> Since you don't bother looking for root cause before closing your issues ... I'll open a new one.

My response on your previously closed issue confirms I look into issues before closing:

> I just tried the download on two different systems, with both the CLI unzip utility as well as the default Archive Utility, and had no problems whatsoever.

I'll paste my response from the other issue:

> I'm sorry to hear that but I assure you the problem is not with the zip file. Again I (and many others) have already successfully downloaded and unzipped it. I myself have verified it using four different PCs, on two different networks, and with three different browsers.

> There is something unique to your setup causing this issue. Either something related to the network, some firewall or Anti-Virus configuration, etc.

> It's only your zip that doesn't open ... i'm gonna go with, it's you, not me.

And it's only you having this problem...nobody else.

**Comment by qcha0s** [comment]
<img width="977" alt="screen shot 2017-11-15 at 9 52 49 am" src="https://user-images.githubusercontent.com/717986/32842357-de408180-c9ea-11e7-82df-9b05c4f1025e.png">

no result from shasum ... like i said, corrupt. I hear the "it works for me" response and I get it ... I really do, but I don't know why this is the only zip on my system with this issue ... thoughts? feedback? .... the src downloads and opens

**Comment by nwoolls** [comment]
Try on other PCs, try on other Networks, try disabling any Anti-Virus or firewalls.
