### ISSUE TITLE
Other Algorithm

### ISSUE THREAD

**Issue by KinGGuN73** [nwoolls/MultiMiner#295]
Is it possible to add miners to mine Ethash, Equihash, Cryptonight ?

**Comment by nwoolls** [comment]
Please see the following topics:

* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms
* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners

**Comment by nwoolls** [comment]
@KinGGuN73 version 4.2 is out and has support for Monero (CryptoNight) and Ethereum (Ethash) mining out-of-the-box.

* https://github.com/nwoolls/MultiMiner/releases/tag/v4.2.0
