### ISSUE TITLE
NeoScrypt not working

### ISSUE THREAD

**Issue by dncndonutz** [nwoolls/MultiMiner#296]
First off, I'm completely new to mining. I was mining a few scrypt coins with no problems, but I've tried two neoscrypt coins on two different pools and get the same error message for each:

> SGMiner is exiting after launching with exit code 1.
> 
> Details: Command line options set a device that doesn't exist
> 
> Executable: C:\\...\MultiMiner\Miners\SGMiner5\SGMiner.exe
> Arguments: --algorithm neoscrypt -o "host/port" -u "user" -p "pass" -d 0 --api-listen --api-port 4028 --api-allow W:127.0.0.1, -T -q --log 5

*obivoulsy "host/port", "user", and "pass" are different, and I can assure you they are correct

Like I said, I'm completely new to mining, so I really have no idea what's going wrong. Can anyone help me out? Thanks in advance.

**Comment by nwoolls** [comment]
SGMiner doesn't think you have a device 0 that is capable of mining. Try running SGMiner directly with the the `/n` argument. What is the output?

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
