### ISSUE TITLE
Equihash miners

### ISSUE THREAD

**Issue by aafanasyev** [nwoolls/MultiMiner#297]
Hi

I am wondering is it possible to configure Equihash miners (nheqminer, Claymore etc) in the Multiminer. I tried but without succes...

Thank you

**Comment by nwoolls** [comment]
Only CGMiner forks and miners that implement the CGMiner RPC API are currently supported. PRs welcome though for additional miner support.

**Comment by nwoolls** [comment]
@aafanasyev version 4.2.1 has out-of-the-box support for mining Equihash coins using SGMiner-GM:

* https://github.com/nwoolls/MultiMiner/releases/tag/v4.2.1
