### ISSUE TITLE
BFG Miner

### ISSUE THREAD

**Issue by Delta691150** [nwoolls/MultiMiner#298]
I have downloaded MultiMiner and set up my Parameters. when I selected Scan for device I receive and error message: 
Miner not found
No copy of BFGMiner was detected. Would you like to download and install BFGMiner now?
I click yes,
progress please wait...
downloading and installing BFGMiner from luke.dashjr.org  followed by a new window,

Copy file
an unexpected error is keeping you from copying the file. If you continue to receive this error, you can use the error code to serch help with this problem.  Error 0x80004005: Unspecified error

I have looked up the error and it seems to be I didn't have an unzipper for rar files which I resolved. I tried both the error search listed winzip 22 and unzipper.

I tried again have the BFG Miner file on my desk top but get the same messages.  is it broken is it in the wrong place where does it go? can someone please help

**Comment by nwoolls** [comment]
Try disabling any antivirus software you may have running. A lot of it will block mining software from being downloaded, copied, etc.

Otherwise try downloading and unzipping BFGMiner 4.9.0 to `Path\To\MultiMiner\Miners\BFGMiner`.

**Comment by Delta691150** [comment]
this worked
