### ISSUE TITLE
No Etherium Support

### ISSUE THREAD

**Issue by matthewmspace** [nwoolls/MultiMiner#299]
If possible, I would like if Etherium mining through ethash in MultiMiner.

**Comment by nwoolls** [comment]
As long as you use the SGMiner fork for ethash it should already be possible using the customizable backend miners and GPU algorithms. I do not have access to a rig capable of mining ETH these days (seems to require a GPU w/ 2GB of RAM) or I'd have already put together and out-of-the-box config.

Please see the following topics for steps that should work:

* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners
* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms

If you'd like to provide secure access to a mining rig or the working config from setting this up I can get a config for this baked in.

**Comment by nwoolls** [comment]
@matthewmspace version 4.2 is out and has support for Monero (CryptoNight) and Ethereum (Ethash) mining out-of-the-box.

* https://github.com/nwoolls/MultiMiner/releases/tag/v4.2.0
