### ISSUE TITLE
multiminer not letting gekko usb miner start

### ISSUE THREAD

**Issue by ghost** [nwoolls/MultiMiner#301]
it does see the miner installed and is listed in hardware as proxy -- problem is pools refuse to connect to this 2pac miner and just sits idle and yes did try all the stuff can find here about usb miners

**Comment by jamie2678** [comment]
finally got it mining but no hash rate displayed

need the hash rate so know if working at designed capacity or not

**Comment by nwoolls** [comment]
@jamie2678 I do not have a Gekko miner so I cannot say how to get one mining and with what backend miner. If there is a version of BFGMiner that supports the Gekko, try placing that inside the `<MultiMiner>\Miners\BFGminer\` folder.

If there is a reseller or user who wants to donate one of these I'd be happy to verify and document support, as I have with previous devices.

**Comment by jamie2678** [comment]
It is mining but just shows no hash rate

Only way know this is watching the datagrid page where it finishes a block and prints the time it took

jamie

-----> Taking donations. donations accepted by credit cards and bitcoin
Doing volunteer counter terror security and donations for cost of doing security and making source of funding for medical expenses so can get away from government insanity keeping people trapped with insane limits punishing people for trying to work. .

________________________________

**Comment by nwoolls** [comment]
@jamie2678 can you use the API Monitor to copy (with CTRL+C) and paste the output of the `DEVS` command being issued to the miner that is running the Gekko?

* https://github.com/nwoolls/MultiMiner/wiki/API-Monitor

**Comment by jamie2678** [comment]
Copy and paste not working when copy from your app so here is from log file

{"DateTime":"2018-01-09T15:31:03.1778734-06:00","Request":"devs","Response":"STATUS=E,When=1515533463,Code=10,Msg=No PGAs,Description=bfgminer 4.9.0|\u0000","CoinName":"Bitcoin","Machine":"127.0.0.1:443"}


________________________________

**Comment by nwoolls** [comment]
@jamie2678 you need to click in the cell you want to copy before hitting CTRL+C.

Can you email me your whole API log? nwoolls @ gmail dot com. The above line you've pasted does not show that BFGMiner is mining, as seen by the `No PGAs`. So either that line does not represent the instance mining using the Gekko or there is something else at play. You mentioned previously that it shows as a "proxy" which it definitely should not - the Stratum Proxy in MulitMiner is something else entirely.

**Comment by jamie2678** [comment]
Some reason copy and paste hates your app and refuses to do this

Did play around and find a different way – have to paste to notepad then copy again

Windows 10 gets screwy

STATUS=E,When=1515534643,Code=10,Msg=No PGAs,Description=bfgminer 4.9.0|

________________________________

**Comment by nwoolls** [comment]
@jamie2678 Can you email me your whole API log file? nwoolls @ gmail dot com. The above line you've pasted does not show that BFGMiner is mining, as seen by the No PGAs. So either that line does not represent the instance mining using the Gekko or there is something else at play. You mentioned previously that it shows as a "proxy" which it definitely should not - the Stratum Proxy in MulitMiner is something else entirely.

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
