### ISSUE TITLE
Crash on changing port # on GUI

### ISSUE THREAD

**Issue by lockboxpm** [nwoolls/MultiMiner#302]
When attempting to add a new pool and change the port from 3333 to X, the 4.1.1 app crashes on my MAC OS X 10.12.6 OS.

**Comment by iLuvLinux** [comment]
X?

**Comment by jamie2678** [comment]
thinking op was using x as any number and not trying to list every possible number since seems actual port number really not matter but fact of having a change does

**Comment by nwoolls** [comment]
@lockboxpm thanks - reproduced. I'll try to get this fixed in the next update.

**Comment by nwoolls** [comment]
@lockboxpm @iLuvLinux @jamie2678 FYI I am not seeing any crash / error on macOS unless attempting to enter a non-numeric value for the port. The crash itself looks to be something within Mono. I will look into addressing it.

**Comment by nwoolls** [comment]
Thanks again all - this is fixed for 4.1.3.
