### ISSUE TITLE
hidden miner

### ISSUE THREAD

**Issue by koalana** [nwoolls/MultiMiner#304]
how do i unhide a networked miner?

**Comment by nwoolls** [comment]
You can edit the file `NetworkDevicesConfiguration.xml` in the MultiMiner settings folder (`%appdata%\MultiMiner` on Windows).

**Comment by koalana** [comment]
there is no  NetworkDevicesConfiguration.xml  in the settings folder (
%appdata%\MultiMiner on Windows).

Gordon

**Comment by nwoolls** [comment]
Make sure you close MultiMiner first. If there is no file there then there have been no network devices discovered on your LAN.

**Comment by koalana** [comment]
then perhaps its a local asic then, its still hidden, found the others,
wish i had not hit the hidden button

**Comment by koalana** [comment]
definitely listed as a Network device.  I have two which show up and the
third i c nowhere.

cant see any xml files at all

Gordon
