### ISSUE TITLE
find network miner

### ISSUE THREAD

**Issue by koalana** [nwoolls/MultiMiner#306]
Hi,
After uninstalling multiminer and then reinstalling, there is one miner I can not find.
It is working but not visible.

Gordon

**Comment by nwoolls** [comment]
Try adding the miner manually to `NetworkDevicesConfiguration.xml`. If it is already present make sure it is not hidden in the XML. If the miner still does not show, MultiMiner is unable to connect within a timely manner - either blocked entirely or the request is timing out due to latency.
