### ISSUE TITLE
MultiMiner settings&issues !

### ISSUE THREAD

**Issue by JohnnyPRD** [nwoolls/MultiMiner#308]
Good afternoon,

I already follow the steps necessary for installation MultiMiner on Linux (Ubuntu 17.10) but without success.
**When I try to launch MultiMiner I receive an error message in which it say that MultiMiner folder missing.**

Beside of this I have some questions for which I didn't found yet any answer, but I hope that I will found some here.
So, my questions are:

1. What is the latest version of Ubuntu (64bit) for which is optimized MultiMiner ?
2. once all GPU's are mounted on the rig, and Ubuntu installed (recommended version, for latest MultiMiner) it is imposed to be made changes in BIOS ? (except case in which not all GPU's are recognized, and is imposed changes in BIOS);
3. It is imposed that based on GPU's use to be installed properly the correct drivers manually ? (my first rig will have 8 GPU's: AMD and NVidia)
4. MultiMiner detect automatic the GPU's type and model ?
5. It is imposed that GPU's to be under-clocked manually for best performance ?  or MultiMiner can do this based on currency choice for mining?
6. Each rig (for more rigs) must have installed MultiMiner ? or can be installed on one PC (as server) and from there to be controlled all rigs (slaves) using MultiMiner ? in this case is important that only the operating system to be installed on all rigs ?

I waiting with higher interest your feedback, to can start to use it.
Any recommendation or advice + links is welcome and appreciate (also I am sure that more users will appreciate advice posted).
Thanks in advice to all members of community for support.

Kind regards.
Johnny

**Comment by nwoolls** [comment]
Please post the exact command you are running and the exact output using copy & paste rather than paraphrasing.

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
