### ISSUE TITLE
bfgminer

### ISSUE THREAD

**Issue by Npizza** [nwoolls/MultiMiner#309]
I tried to run sudo add-apt-repository ppa:unit3/bfgminer and i get
'This PPA does not support xenial'
Cannot add PPA: ''This PPA does not support xenial''.
what can i do?

**Comment by nwoolls** [comment]
This is beyond the scope of this project or repo. Please look into installing BFGMiner on your Linux distro and then you should be able to use MultiMiner. BFGMiner comes with installation instructions. Or try searching for the error code you are receiving:

* https://www.google.com/search?q=%27%27This+PPA+does+not+support+xenial%27%27
