### ISSUE TITLE
MultiMiner4.1.1 diagnosed as a virus by Avast

### ISSUE THREAD

**Issue by crsn** [nwoolls/MultiMiner#310]
MultiMiner 4.1.1 downloaded from release pages (link: https://github.com/nwoolls/MultiMiner/releases/download/v4.1.1/MultiMiner-4.1.1.exe ) is reported to be a virus by Avast. Windows won't install it.
Please consider to add checksum of single file downloads to your download page.

**Comment by nwoolls** [comment]
@crsn please see the already closed issues regarding this. Most / all mining software will be flagged and, if it isn't today, it will be tomorrow.

**Comment by velum** [comment]
And why is that? Why are they getting flagged?
JF


Envoyé de Yahoo Courriel pour iPhone


Le mardi, décembre 12, 2017, 4:04 PM, Nate Woolls <notifications@github.com> a écrit :


@crsn please see the already closed issues regarding this. Most / all mining software will be flagged and, if it isn't today, it will be tomorrow.

**Comment by nwoolls** [comment]
https://www.google.com/search?q=why+is+mining+software+flagged+as+a+virus

**Comment by crsn** [comment]
I understand @nwoolls. Would you consider to write about that in the download page, to help newbies like me? Thanks
