### ISSUE TITLE
MultiMiner crashes on "Downloading and Installing BFGMiner from luke.dashjr.org"

### ISSUE THREAD

**Issue by TheGamePlayer** [nwoolls/MultiMiner#312]
![not](https://user-images.githubusercontent.com/28575885/34105054-1966fb6e-e3da-11e7-8525-e5f5836bef7b.png)

**Comment by nwoolls** [comment]
Try disabling any antivirus software you may have installed. If that fails install BFGMiner manually yourself. See the following for more info:

* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners
