### ISSUE TITLE
Don't Start on MacOS 10.13.2

### ISSUE THREAD

**Issue by s1rleblanc** [nwoolls/MultiMiner#314]
I try to use on my Macbook Pro Retina and it says: "The application "MultiMiner" can not be opened".

and when i try on command line it says: LSOpenURLsWithRole() failed with error -10810 for the file /path/to/MultiMiner.app.

i try this to: $ mono --arch=32 MultiMiner.Win.exe

but it just hangs up and does nothing.

Can any one help me please ? Thank you!

**Comment by nwoolls** [comment]
> i try this to: $ mono --arch=32 MultiMiner.Win.exe
> 
> but it just hangs up and does nothing.

Wait longer. It can take some time for XQuartz to run. There should be *some* output, not *no* output.

**Comment by s1rleblanc** [comment]
Thank you its works, but.. can i run this from the APP framework ? i mean don't enter on command line to run it.

I try the newest version and can't run it from the APP it says the same "The application "MultiMiner" can not be opened".

Thank you!

**Comment by nwoolls** [comment]
@s1rleblanc try downloading version 4.1.2 from http://downloads.multiminerapp.com - even if you already downloaded that version. There was a fix to the `.app` package after release and I put up a new file.

Secondly, make sure the `.app` file does not have a space in it. If you have downloaded multiple versions, for instance, and extracted them to the same spot it may be named `MultiMiner 2.app` by OS X. Rename it to something without a space.

If that still fails, try doing the following from a Terminal prompt and report back the output: `open /path/to/MultiMiner.app`.

**Comment by s1rleblanc** [comment]
here is the result 
$ open MultiMiner.app/
LSOpenURLsWithRole() failed with error -10810 for the file /My/user/Downloads/MultiMiner.app.

just the same error

**Comment by nwoolls** [comment]
What is the output of `which mono`?

**Comment by acidos** [comment]
Same here
**LSOpenURLsWithRole() failed with error -10810 for the file /Applications/MultiMiner.app.**
10.13.1 (17B48)
`which mono` doesn't output anything

**Comment by acidos** [comment]
after kill/restart I could see UI and configure pool. But the start button is not active.
Looks like the mining hardware(GPU of Macbook Pro 2016) is not found.

**Comment by s1rleblanc** [comment]
My dear @nwoolls you don't will believe me when i tell you how i fix the problem... 

just $ chmod +x ~/MultiMiner.app/Contents/MacOS/MultiMiner.Win

**Comment by nwoolls** [comment]
@acidos yes you need to install Mono first and no embedded GPUs are not likely to be usable. Out of the box you'd need an AMD GPU.

@s1rleblanc you would need to compile BFGMiner yourself with the CPU mining flag enabled. I do not distribute these builds as they are often used for malware.
