### ISSUE TITLE
Is it possible to add ewbf-miner for equihash?

### ISSUE THREAD

**Issue by zoglun** [nwoolls/MultiMiner#315]
ewbf-miner isn't the fastest miner. But it can achieve 4.4 Sol/Watt, while the DSTM currently came with MultiMiner only get 4.05 with same OC settings. (using GTX 1070 Ti)

My concern is that MultiMiner been wrote to value hashrate out put more than efficiency. Therefore ewbf-miner might not been picked by the program.

**Comment by nwoolls** [comment]
You can add any miner as long as it is a CGMiner, BFGminer, or SGMiner fork with compatible command line arguments and API. Supporting any other miners would require additional work that I am not willing to do, but I welcome PRs to add the feature.

* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners
* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms

**Comment by zoglun** [comment]
Cool. Thank you!

**Comment by nwoolls** [comment]
@zoglun version 4.2.1 has out-of-the-box support for mining Equihash coins using SGMiner-GM:

* https://github.com/nwoolls/MultiMiner/releases/tag/v4.2.1
