### ISSUE TITLE
Hey Pls Add Cryptonote mining on MultiMiner

### ISSUE THREAD

**Issue by LaMuerteMRT** [nwoolls/MultiMiner#317]
hola, debería agregar cryptonote en el programa porque no encuentro ninguna forma de extraer cryptonote en el programa, creo que al desarrollador no le costaría mucho agregar ese formato para extraer nuevas monedas (también debe agregar la opción para detectar CPU) PLS PLS PLS PLS

**Comment by nwoolls** [comment]
Please see the following topics. You can add any coin, algorithm, and miner to MultiMiner as long as it is a CGMiner, BFGMiner or SGMiner fork.

* https://github.com/nwoolls/MultiMiner/wiki/Crypto-Coins
* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms
* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners

**Comment by LaMuerteMRT** [comment]
but I can not find a way to add cryptonote algorithm :(

**Comment by nwoolls** [comment]
Please read the following more carefully - you can click the *Add* button to add a new algorithm:

* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms

**Comment by nwoolls** [comment]
@LaMuerteMRT version 4.2 is out and has support for Monero (CryptoNight) and Ethereum (Ethash) mining out-of-the-box.

* https://github.com/nwoolls/MultiMiner/releases/tag/v4.2.0
