### ISSUE TITLE
No Cryptonote in Option Select program And Miner incompatible Cryptonote :(

### ISSUE THREAD

**Issue by LaMuerteMRT** [nwoolls/MultiMiner#318]
hello, I should add cryptonote in the program because there is no way to extract cryptonote in the program, I think the developer would not have much trouble adding that format to extract new currencies but I can not find a way to add cryptonote algorithm :( on no side of the list does cryptonote appear. It's impossible for me to mine Monero...

I also tried to put the command myself by adding cryptonote and the variable - cryptonote and - crypto algorithm, but the miners that the program incorporates do not accept and give error.

I put down the list of algorhythms that if accepted and as can be seen is not this cryptonote :(

https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms
GPU Algorithms
MultiMiner ships with support for numerous GPU algorithms out-of-the-box, including:

SHA-256
Scrypt
Scrypt-N
Scrypt-Jane
NeoScrypt
Keccak
Groestl
Quark
Lyra2RE
X11, X13, X14, and X15
??? No cryptonote ??

More importantly, the user can easily add support for any algorithm by providing a compatible backend miner.

I also see that my miner works but does not connect with the pool. in this case I am trying with ltc because I do not achieve with monero. but it does not work either :(
![a7d79fb9c1041f28703219bb5ac0b9a5](https://user-images.githubusercontent.com/13895945/34343125-9180353a-e9c4-11e7-9ced-38d66d598965.png)

**Comment by nwoolls** [comment]
Please see the following topics. You can add any coin, algorithm, and miner to MultiMiner as long as it is a CGMiner, BFGMiner or SGMiner fork.

* https://github.com/nwoolls/MultiMiner/wiki/Crypto-Coins
* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms
* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners

**Comment by nwoolls** [comment]
@LaMuerteMRT version 4.2 is out and has supports for Monero (CryptoNight) and Ethereum (Ethash) mining out-of-the-box.

* https://github.com/nwoolls/MultiMiner/releases/tag/v4.2.0
