### ISSUE TITLE
Mining fault, no shares, no aceptes,

### ISSUE THREAD

**Issue by LaMuerteMRT** [nwoolls/MultiMiner#319]
Hi, I have a bug and I do not know how to fix it, attached screenshot

![8ee7c59e7be1a31d32f9dca2874b6f2b](https://user-images.githubusercontent.com/13895945/34344025-a0f80652-e9e0-11e7-9096-40f69c93bb9c.png)

**Comment by nwoolls** [comment]
@LaMuerteMRT there is no bug in your attached screenshot. It's just showing a miner running. Wait longer if you want to see accepted shares. Much longer depending on the difficulty. That is a very slow miner (these days).
