### ISSUE TITLE
Help error: No miner defined for algorithm..

### ISSUE THREAD

**Issue by Lowerman** [nwoolls/MultiMiner#321]
![image](https://user-images.githubusercontent.com/11877891/34464440-d0c30a24-ee65-11e7-9e16-86d92661e93e.png)

how i define the miner for x algorithm?

**Comment by nwoolls** [comment]
@Lowerman please see the following entry on the wiki:

* https://github.com/nwoolls/MultiMiner/wiki/GPU-Algorithms

**Comment by nwoolls** [comment]
Also:

* https://github.com/nwoolls/MultiMiner/wiki/Backend-Miners
