### ISSUE TITLE
Ubuntu PPA not required anymore -> update docu

### ISSUE THREAD

**Issue by fossler** [nwoolls/MultiMiner#323]
The ppa:unit3/bfgminer PPA contains only old packages.
https://launchpad.net/~unit3/+archive/ubuntu/bfgminer

BFGminer is now officially in the Ubuntu repositories and contains packages for all currently supported Ubuntu versions.
https://launchpad.net/ubuntu/+source/bfgminer

You can install BFGminer by issuing:
`sudo apt-get install bfgminer
`

**TODO**
Documentation needs to be updated here and on the homepage.

**Comment by nwoolls** [comment]
Thanks - docs updated here:

* https://github.com/nwoolls/MultiMiner/wiki/Installation
