### ISSUE TITLE
bfgminer cannot mine using cpu

### ISSUE THREAD

**Issue by glennpamisa** [nwoolls/MultiMiner#327]
i tried to follow the tutorial in the website but i didn't understand it please show me another way send the information to this email : kevinnyiwa@gmail.com

**Comment by nwoolls** [comment]
@glennpamisa you will need to compile BFGMiner to include CPU mining or download a copy of BFGMiner that already has CPU mining enabled. The version I distribute does not include CPU mining as that is frequently used for malware and viruses.

**Comment by glennpamisa** [comment]
can you send me the BFGminer that has CPU enabled to my email: kevinnyiwa@gmail.com
