### ISSUE TITLE
bfgminer wont install - Windows 10

### ISSUE THREAD

**Issue by pookie1** [nwoolls/MultiMiner#329]
New to the scene, trying to install bfgminer. Keeps returning error code 0x80004005 saying it cannot copy a file, and won't continue to install :(

Arghhh... not a great start.

Ideas ?

Cheers.

**Comment by nwoolls** [comment]
Disable antivirus, anti-malware, Windows Defender, etc. Something at the system level is blocking the installation of crypto mining software.

**Comment by pookie1** [comment]
Hi,
Thanks for your reply :)
I have disabled the things you suggested, but it still gives the same error :(
PJ
