### ISSUE TITLE
Still getting same error on install - Windows 10

### ISSUE THREAD

**Issue by pookie1** [nwoolls/MultiMiner#330]
![screenshot 13](https://user-images.githubusercontent.com/35513067/35040675-29156fe6-fbd6-11e7-9404-0fc233c4d3d0.png)

I have turned off all antivirus etc...  but still same error :(   very frustrating.

Plz help :)

**Comment by nwoolls** [comment]
Download BFGMiner manually and extract it to `<MultiMiner>\Miners\BFGMiner`.
