### ISSUE TITLE
ethermine.org config?

### ISSUE THREAD

**Issue by pdarcos** [nwoolls/MultiMiner#331]
Hi,

Thanks for this great software!
I'm trying out the new ether mining in the latest release but I'm probably making a stupid mistake since it fails to connect to the pool.

I'm using ethermine.org and they don't use workers with passwords, but rather this format:

ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>

I've tried putting -O myethereumaddress in the Pool arguments pane but I keep pool connection error messages. Where can I put my wallet address?

Any hints?

Thanks

**Comment by nwoolls** [comment]
Put your Ethereum address in the *Worker name* field when configuring the pool.

**Comment by pdarcos** [comment]
hanks for the quick reply!
I've tried that and I still get the launching Miner Failed error message along with verify pool settings.

I've tried inputting the wallet address in the Worker name field (with and without the leading 0x) and leaving the password blank, putting in a random password, and nothing has worked.

I'm a linux guy and am coming from ethos where I had it running fine. Where can I find the debug logs for the pool connection so I can see what's going on?

Thanks

**Comment by nwoolls** [comment]
@pdarcos switch to the *Process Log* screen, find the failed entry, and you can right-click and launch the miner from there to see the direct output (you will need to click *Stop* first if mining). You can also see the args passed to the miner on the *Process Log* screen. There are also log files as well. Check the wiki topics:

* https://github.com/nwoolls/MultiMiner/wiki/Process-Log
* https://github.com/nwoolls/MultiMiner/wiki/Log-Files

**Comment by pdarcos** [comment]
Thanks @nwoolls 
I ended up reinstalling from scratch and now it's working OK
