### ISSUE TITLE
Does not detect single GPU on ubuntu

### ISSUE THREAD

**Issue by aleksanyan** [nwoolls/MultiMiner#332]
I tried setting up MultiMiner (v4.2.2) on Ubuntu 16.04. All the setup process went smooth and I've opened 
GUI thru 'mono MultiMiner.Win.exe'. The only issue with it is it does not show any device with which I can mine. 
P.s I have EWBF miner setup with nvidia drivers, which is working with GPU on same machine.

**Comment by nwoolls** [comment]
@aleksanyan what GPU? This uses SGMiner and BFGMiner so only AMD devices are supported.

**Comment by aleksanyan** [comment]
I see, unfortunately mine is Nvidia 1070 ti. Thanks for the reply.

**Comment by nwoolls** [comment]
@aleksanyan no problem
