### ISSUE TITLE
setting the multiminer to mint

### ISSUE THREAD

**Issue by pavel996** [nwoolls/MultiMiner#337]
I set up the miner on windows- 15 minutes and everything works. But there were problems with installing on mint. My algorithm of actions:
1) I read the instruction:
Linux Installation (Debian-Based)
Install the latest version of Mono

sudo apt-get install mono-complete
Install your chosen mining engine

sudo add-apt-repository ppa: unit3 / bfgminer
sudo apt-get update
sudo apt-get install bfgminer
Download and extract the .zip file at the GitHub Releases page

Run MultiMiner.Win.exe using mono:

mono MultiMiner.Win.exe
2) Install the latest version of Mono                                                                - did it, it turned out
3) Install your chosen mining engine                                                              - did it, it turned out
4) Download and extract the .zip file at the GitHub Releases page               - did, it turned out
5) Run MultiMiner.Win.exe using mono                                                          - miner started, but there is one problem: miner does not determine the video card, there is an assumption that scan hardware does not start.

**Comment by nwoolls** [comment]
Run BFGMiner with the `-h` argument and ensure it is compiled with the _opencl_ driver as seen below:

```
./bfgminer -h
bfgminer 5.5.0-unknown
  Lowlevel: ftdi hid pci pci:uio spi usb vcom
  Drivers: antminer avalon avalonmm bfx bifury bigpic bitforce bitforce:pci bitfury cairnsmore cointerra compac drillbit dualminer erupter gridseed hashbuster hashbusterusb hashfast icarus klondike littlefury modminer nanofury opencl proxy proxy:getwork proxy:stratum rockminer twinfury x6500 zeusminer ztex
  Algorithms: Keccak SHA256d scrypt
  Options: ncurses
```

If you do not see the OpenCL driver you will need to install (or compile) a version of BFGMiner with the _opencl_ driver enabled.

If the _opencl_ driver is enabled, run the following command. It should list your OpenCL devices. If not, check with the BFGMiner author / support in their [respective thread](https://bitcointalk.org/index.php?topic=877081.0) / [issue tracker](https://github.com/luke-jr/bfgminer/issues).

```
./bfgminer -S auto -d?

 [2018-02-04 12:05:21] Started bfgminer 5.5.0-unknown
 [2018-02-04 12:05:23] /dev/cu.usbmodem3A21 is already in use by another process
 [2018-02-04 12:05:23] Devices detected:
 [2018-02-04 12:05:23]  Device (driver=opencl; procs=1)
1 devices listed
```
