### ISSUE TITLE
Руссфикация MultiMiner, не намечается ?

### ISSUE THREAD

**Issue by RTlisov** [nwoolls/MultiMiner#343]

**Comment by RTlisov** [comment]
Все сложно, но интересно :)

**Comment by nwoolls** [comment]
Can you describe the problem you are having or the enhancement you are requesting in English please?

**Comment by RTlisov** [comment]
As such there is no problem. Wanted to learn Russian language will be supported in the future ?

**Comment by nwoolls** [comment]
@RTlisov there is no plan to translate / localize MultiMiner but I'd be happy to merge any Pull Requests for localizations.
