### ISSUE TITLE
preconfiguration

### ISSUE THREAD

**Issue by easyminer** [nwoolls/MultiMiner#351]
Is there a way of preconfiguring multiminer with pool address, etc so a downloader of the software doesnt need to configure anything. Just install and go.....

**Comment by nwoolls** [comment]
@easyminer yes if someone wants a branded version of MultiMiner that can be done - for a fee - and it includes out-of-the-box pool config along with a host of other things (changing the default algo, default coin, setting default pool, specifying default flags for miners, alternative downloads for updates, etc).

**Comment by easyminer** [comment]
ok.. how much will that fee be?

**Comment by nwoolls** [comment]
@easyminer feel free to reach out to nwoolls @ gmail.com

**Comment by easyminer** [comment]
I emailed you
