### ISSUE TITLE
issues starting in mono 

### ISSUE THREAD

**Issue by theyboosting** [nwoolls/MultiMiner#356]
I've followed the documentation to a T, but unfortunately I'm receiving what I'm sure is a common error. Please forgive my ignorance.

sbk@sidebitches:~/Downloads$ mono --arch=32 MultiMiner-4.2.3.exe 
Unknown command line option: '--arch=32'
sbk@sidebitches:~/Downloads$ mono  MultiMiner-4.2.3.exe 
Cannot open assembly 'MultiMiner-4.2.3.exe': File does not contain a valid CIL image.
sbk@sidebitches:~/Downloads$ uname -a 
Linux sidebitches 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Thank you in advance.

**Comment by nwoolls** [comment]
@theyboosting 

1. Either install a newer version of Mono or omit the `--arch=32` argument
1. Download the ZIP file from the releases page *not* the Windows installer - you should be running the command on `MultiMiner.Win.exe` not `MultiMiner-X.Y.Z.exe`

For more information, see:

* https://github.com/nwoolls/MultiMiner/wiki/Installation#linux-installation-debian-based

**Comment by theyboosting** [comment]
Thank you very much , I will try that now.. 

I'm assuming mono is the newest version since it was installed via git less than 30mins ago 

trying the zip'd installer now, will report back.

**Comment by theyboosting** [comment]
picking the correct executable worked, Thank you.. Its been many years since I've used a windows.exe lol
