### ISSUE TITLE
lyra2rev2 not supported, adding custom coins not supported, coin configuration gets erased

### ISSUE THREAD

**Issue by airatru** [nwoolls/MultiMiner#362]
Greetings,
I've tried to point multiminer to my verge wallet to setup local network stratum proxy for multiple rigs and failed. MM doesn't allow to add any coin not on the list (a lot of coins not on the list), and also doesn't allow to add existing coins but with not listed algos. If I try adding Verge with lyra2rev2, it would add verge with scrypt and then say that pool is not configured right. anything else just wont even give ability to start it. In pool configuration menu, anything I type into pool port number field gets erased and overwritten with 80. 
I really hope that MM will support lyra2rev2 algo and its coins.

**Comment by nwoolls** [comment]
@airatru make sure you are running version 4.2.3 from http://downloads.multiminerapp.com. I am not able to reproduce any of the above. Below find a brief screencast that demonstrates that

1. Lyra2Rev2 is supported out-of-the-box and does not need to be added
1. Adding a new coin is properly saved

This was with a new installation of 4.2.3 without any other previous configuration.
