### ISSUE TITLE
mono32 not responding in the downloading process of bfgminer

### ISSUE THREAD

**Issue by whitelist17** [nwoolls/MultiMiner#363]
mono32 not responding in the downloading process of bfgminer...i have intego for antivirus software as well as little snitch. But intego should firewall is off and little snitch is in silent mode.

**Comment by nwoolls** [comment]
@whitelist17 install BFGMiner manually. MultiMiner only downloads it if it does not already exist on the system. e.g. in `/usr/local/bin/bfgminer`.
