### ISSUE TITLE
USB miner

### ISSUE THREAD

**Issue by paul5066** [nwoolls/MultiMiner#364]
I have a GekkoScience 2PAC (Dual BM1384) USB Stickminer and it is showing as an Antminer. I have installed the USB drivers as per docs.  It will not work.

Error is "DateTime":"2018-05-02T21:44:10.7086013-04:00","Request":"devs","Response":"STATUS=E,When=1525311850,Code=10,Msg=No PGAs,Description=bfgminer 4.9.0|\u0000","CoinName":"Verge-Scrypt","Machine":"127.0.0.1:4029". From the log file.

I was reading the setup information and saw the section FTDI drivers and the use for dual miners. 

Would like to be sure this is what I need before installing. Have there been ant other problems like this that have been fixed with FTDI driver?

Paul

**Comment by nwoolls** [comment]
@paul5066 AFAIK the underlying USB miner (BFGMiner) does not support that particular ASIC:

* https://github.com/luke-jr/bfgminer/issues/692
