### ISSUE TITLE
how to force multiminer to use cpu? 

### ISSUE THREAD

**Issue by amirbaseball** [nwoolls/MultiMiner#374]
hi, guys, I can't find any article on how to get multiminer to use CPU instead of gpu!

**Comment by ThatSkepticalGamer** [comment]
CPU Mining is pretty bad. You might be better of using your GPU, even if its low range. If, for some strange reason, you do want to use the CPU to mine, try using a different app. I recommend GUIMiner for CPU Mining.

**Comment by nwoolls** [comment]
@amirbaseball you will need to compile BFGMiner w/ CPU mining support. After that, MultiMiner will support CPU mining. BFGMiner does not ship with CPU mining support due to the use of the resulting binary by malware authors.
