### ISSUE TITLE
Is My Pool Set Correctly?

### ISSUE THREAD

**Issue by F0urL34f** [nwoolls/MultiMiner#378]
Hello All!,
I've Currently Got MM Running With a GTX960 4GB And I Was Just Curious If Anyone could help me out. Now Just For Fun I'm Attempting to Mine a single Block on FeatherCoin with NeoScrypt.
The Miner Seems To Be Running Perfectly Fine, but I'm concerned I haven't entered the correct credentials if I was to solve a block and have the coins transferred to my desktop wallet (Elect).
Current Work : 471 Works / 117 Accepted Shares / 0 rejections / 29 khs (lol).
GPU running a steady 60* C with no hiccups.
I'm Under the impression without finding much online that to make a new coin miner you would:
1. Go To Pools
2. Add Coin
3. Drop Down to NeoS and Select FTC
4. Add Your Wallet ID Address (Starting with a 6) INFRONT of the pre filled in stratum+tcp://
Can Anyone Please Confirm With The Above Set Up If I Am To Solve A Coin Will It Be Properly Transferred? THANK YOU!

**Comment by jmiguel99** [comment]
I think  you need to add the pool server address there, and  then you put the wallet address in the worker blank space

**Comment by nwoolls** [comment]
This all depends on your pool, but generally no you do not put the wallet address in the _Host_ field. Your pool should have a page that tells you the host, port, worker name (user name), and password to enter.
