### ISSUE TITLE
Can not find the miner via VPN

### ISSUE THREAD

**Issue by TMit** [nwoolls/MultiMiner#379]
I could not find the my miner via VPN. Even can not find the low latency one (ping time over 500ms?)

**Comment by nwoolls** [comment]
Check the following post:

* https://github.com/nwoolls/MultiMiner/wiki/Network-Devices

You can also try enabling the options to scan class A and B subnets:

* https://github.com/nwoolls/MultiMiner/wiki/Settings#advanced-application-settings

If that does not work, you can try adding the network device manually by editing `%appdata%\MultiMiner\NetworkDevicesConfiguration.xml`. An entry would look like e.g.:

```
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfNetworkDevice xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NetworkDevice>
    <IPAddress>192.168.0.199</IPAddress>
    <Port>4028</Port>
    <Sticky>true</Sticky>
    <Hidden>false</Hidden>
    <RecentCommands />
  </NetworkDevice>
</ArrayOfNetworkDevice>
```
