### ISSUE TITLE
conect nicehash power rent to proxy

### ISSUE THREAD

**Issue by pouryaeman** [nwoolls/MultiMiner#380]
hi dear
i want many miner ( nicehash power rented - miningrigrental  rig rented ) conect to multipool and switch pool without restart miners
but i creat proxy but nicehash checked and show null eror 
resault:

Pool host: 2.56.213.125
Pool port: 7412
Pool user: x
Pool pass: x
Algorithm: DaggerHashimoto

Resolving pool host 2.56.213.125... OK
Establishing connection with proxy... OK
Establishing connection with pool 2.56.213.125:7412... OK
Sending mining.subscribe... OK
Sending mining.authorize... OK
Received mining.notify subscription... OK
Received authorization result... OK
Error: Read timed out

**Comment by nwoolls** [comment]
Sounds like something you'd need to check with NiceHash support on. The proxy in MultiMiner is using BFGMiner under the hood. You can launch BFGMiner directly, with the proxy enabled, bypassing MultiMiner, using the _Process Log_ screen:

* https://github.com/nwoolls/MultiMiner/wiki/Process-Log
