### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by alpha-denahi** [nwoolls/MultiMiner#381]
I wanted to get into mining, however I changed my mind on using multiminer, but now I cannot uninstall it. I've tried going through the control panel, the settings, and I can't find the uninstall file. I downloaded it from this page on GitHub, but it's virtually invisible on my computer. Some one please help me.

**Comment by nwoolls** [comment]
It shows under "Add / Remove Programs" in Windows as with any other applications. You can also run `unins000.exe` found in the installation folder for MultiMiner. You can get there by going to the shortcut properties and clicking _Open File Location_.
