### ISSUE TITLE
BFGMiner is not being installed automatically

### ISSUE THREAD

**Issue by celsohenrique81** [nwoolls/MultiMiner#388]
The MultiMiner is not installing the BFGMiner automatically in a new installation. It shows the dialog about the issue, ask to download, I click on button YES then it shows the dialog again.

After some tries, I click on button NO and receive this message.

![bfgminer](https://user-images.githubusercontent.com/60555859/73847351-dc38cb00-4804-11ea-95f1-563e0bf31b07.PNG)

It is creating the folders, but is not downloading the files. I think that the problem could be the download link. I had to download manually.

**Comment by nwoolls** [comment]
This is because BFGMiner files are no longer hosted on luke.dashjr.org - see: http://luke.dashjr.org/programs/bitcoin/files/bfgminer/

You can download the files manually from bfgminer.org and unzip them into `MultiMiner\Miners\BFGMiner\` to get around this until I put up an update that fixes this.

**Comment by celsohenrique81** [comment]
Could you create a field to set this (and others) download link manually?

**Comment by nwoolls** [comment]
@celsohenrique81 no, but I'd welcome a PR for this. I am not actively developing this or mining anymore and haven't been for a few years. Just fixing a few bugs that have popped up.

**Comment by nwoolls** [comment]
Fixed in 4.3.1:

* https://github.com/nwoolls/MultiMiner/releases/tag/v4.3.1
