### ISSUE TITLE
Does not get passed installing CG Miner

### ISSUE THREAD

**Issue by ImMX96** [nwoolls/MultiMiner#414]
"Please wait while cgminer is downloaded from asdf.com and installed into folder c:\whatever"

My install does not get past this, if I close it then re-open the app it loads in and fails to install BFGMiner. There is no miners folder and creating one did not help. I have re-installed it and deleted the folders. What do I do? 

(None of the fixes mentioned in any other issue thread have worked so I would appreciate no copy and pastes.)

**Comment by vamtic** [comment]
same
