### ISSUE TITLE
Clicking on other MultiMiner instances on the network freezes (Ubuntu only)

### ISSUE THREAD

**Issue by jmordica** [nwoolls/MultiMiner#89]
When clicking other MultiMiner boxes on the network, the Ubuntu instance of MultiMiner freezes and the whole desktop locks up. Unable to close the app or anything. Have to ssh into the box and reboot.

I've done this multiple times so this is replicable. Ubuntu 12.04 using latest mono and 2.8.3 of MultiMiner.

**Comment by nwoolls** [comment]
I'm not able to reproduce this with Ubuntu 16.04 and MultiMiner 4.2.2. Please reopen if this issue persists for you.
