### ISSUE TITLE
Unhandled Exception in .net

### ISSUE THREAD

**Issue by RFHarwood** [nwoolls/MultiMiner#97]
Here is the details of the dialog:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MultiMiner.Win.Forms.MinerForm.ShowCoinChangeNotification() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 6414
   at MultiMiner.Win.Forms.MinerForm.StartMiningLocally() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 6639
   at MultiMiner.Win.Forms.MinerForm.CheckIdleTimeForDynamicIntensity(Int64 timerInterval) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 6752
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6413 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll

MultiMiner.Win
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Win.exe

System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6402 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

MultiMiner.Engine
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Engine.DLL

MultiMiner.Utility
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Utility.DLL

MultiMiner.Xgminer.Api
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Xgminer.Api.DLL

MultiMiner.Xgminer
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Xgminer.DLL

System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6411 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.6387 built by: Win8RTM
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll

Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6387 (Win8RTM.050727-6300)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6411 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

vhvkkv7w
    Assembly Version: 2.8.4.179
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

xkkwmify
    Assembly Version: 2.8.4.179
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

MultiMiner.Discovery
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Discovery.DLL

MultiMiner.Remoting
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Remoting.DLL

System.Web.Extensions
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.6407
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Web.Extensions/3.5.0.0__31bf3856ad364e35/System.Web.Extensions.dll

System.Web.Abstractions
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.6387
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Web.Abstractions/3.5.0.0__31bf3856ad364e35/System.Web.Abstractions.dll

System.Web
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6414 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_64/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll

pqpczv1i
    Assembly Version: 2.8.4.179
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

wfuzqk39
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

MultiMiner.CoinWarz
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.CoinWarz.DLL

MultiMiner.CoinApi
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.CoinApi.DLL

MultiMiner.CoinChoose
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.CoinChoose.DLL

ciithk-o
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

Newtonsoft.Json
    Assembly Version: 4.5.0.0
    Win32 Version: 5.0.8.16617
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/Newtonsoft.Json.DLL

MultiMiner.Coinbase
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Coinbase.DLL

iz5icx1r
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

mft8hr20
    Assembly Version: 2.8.4.179
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

6sfaasnk
    Assembly Version: 2.8.4.179
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

ycmdi-f_
    Assembly Version: 2.8.4.179
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

Interop.IWshRuntimeLibrary
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/Interop.IWshRuntimeLibrary.DLL

pf04pzqp
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

g1zqwil8
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

MultiMiner.Stats
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Stats.DLL

l8nebmyq
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

MultiMiner.Xgminer.Discovery
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.Xgminer.Discovery.DLL

MultiMiner.MobileMiner
    Assembly Version: 2.8.4.179
    Win32 Version: 2.8.4.179
##     CodeBase: file:///C:/Users/Administrator/AppData/Local/MultiMiner/MultiMiner.MobileMiner.DLL

bkzsksyv
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

yryocbt8
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

ah-zqypu
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

nu4xmi_d
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

yqonujzc
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

cl2ge0_e
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

l7zrnj0g
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.ComponentModel.DataAnnotations
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.6387
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/3.5.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll

System.Runtime.Serialization
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.4506.6401 (Win8RTMGDR.030729-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Serialization/3.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.6387 built by: Win8RTM
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml.Linq/3.5.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6387 (Win8RTM.050727-6300)
##     CodeBase: file:///C:/Windows/assembly/GAC_64/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll

ovdhj8vv
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

y31djwqs
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.6401 (Win8RTMGDR.050727-6400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by shtse8** [comment]
I have the same problem on the latest release.
